// Generated by tools/check_unreal_core_module.py --write; do not edit.
// Compiles battle/src/sim.cpp inside the SovereignCore module (the battle simulation stays engine-independent).
#include "battle/src/sim.cpp"
