// Generated by tools/check_unreal_core_module.py --write; do not edit.
// Compiles core/src/trade.cpp inside the SovereignCore module (the core stays engine-independent).
#include "core/src/trade.cpp"
