// Generated by tools/check_unreal_core_module.py --write; do not edit.
// Compiles core/src/victory.cpp inside the SovereignCore module (the core stays engine-independent).
#include "core/src/victory.cpp"
