// Generated by tools/check_unreal_core_module.py --write; do not edit.
// Compiles diplomacy/src/conversation.cpp inside the SovereignCore module (the dialogue layer stays engine-independent).
#include "diplomacy/src/conversation.cpp"
