// Generated by tools/check_unreal_core_module.py --write; do not edit.
// Compiles net/src/protocol.cpp inside the SovereignCore module (the session protocol stays engine-independent).
#include "net/src/protocol.cpp"
