"""Generate Markdown reference tables for specs/civ6/data/ from a database
built by build_db.py.

Usage:
    python extract.py [path/to/civ6_gs.sqlite] [output_dir]

All effect text is generated from Modifiers / Requirements by effects.py, so
nothing from the game's localization files is copied except proper names.
"""
from __future__ import annotations

import os
import sqlite3
import sys
from collections import defaultdict

from effects import Renderer
from names import Names, md_escape

HEADER = (
    "<!-- Generated by tools/civ6_extract/extract.py from a local Civilization VI install "
    "(Gathering Storm ruleset + installed DLC, no optional game modes). Do not edit by hand. -->\n\n"
)

ERA_ORDER = [
    "ERA_ANCIENT", "ERA_CLASSICAL", "ERA_MEDIEVAL", "ERA_RENAISSANCE", "ERA_INDUSTRIAL",
    "ERA_MODERN", "ERA_ATOMIC", "ERA_INFORMATION", "ERA_FUTURE",
]


class Ctx:
    def __init__(self, db_path: str):
        self.db = sqlite3.connect(db_path)
        self.db.row_factory = sqlite3.Row
        self.n = Names(self.db)
        self.r = Renderer(self.db, self.n)

    def q(self, sql, *args):
        return self.db.execute(sql, args).fetchall()

    def has_table(self, t):
        return bool(self.q("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", t))

    def owner(self, trait) -> str:
        """Civilization or leader that owns a trait (for 'unique to' columns)."""
        if not trait:
            return ""
        if not hasattr(self, "_owners"):
            self._owners = {}
            for t, civ in self.q("SELECT TraitType, CivilizationType FROM CivilizationTraits"):
                self._owners.setdefault(t, self.n(civ))
            for t, ld in self.q("SELECT TraitType, LeaderType FROM LeaderTraits"):
                self._owners.setdefault(t, self.n(ld))
        return self._owners.get(trait, self.n(trait))

    def multi(self, sql, *args) -> dict:
        out = defaultdict(list)
        for row in self.q(sql, *args):
            out[row[0]].append(row[1])
        return out


def table(headers, rows) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    for r in rows:
        out.append("| " + " | ".join(md_escape(c) for c in r) + " |")
    return "\n".join(out) + "\n"


def yesno(v):
    return "yes" if v in (1, "1", True, "true") else ""


def num(v):
    if v is None:
        return ""
    if isinstance(v, float) and v == int(v):
        return str(int(v))
    return str(v)


def write(outdir, fname, title, intro, sections):
    path = os.path.join(outdir, fname)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        f.write(f"# {title}\n\n")
        if intro:
            f.write(intro.strip() + "\n\n")
        for heading, body in sections:
            if heading:
                f.write(f"## {heading}\n\n")
            f.write(body.rstrip() + "\n\n")
    return path


def yields_str(c: Ctx, pairs):
    parts = []
    for y, amt in pairs:
        if amt:
            parts.append(f"{'+' if amt > 0 else ''}{num(amt)} {c.n(y)}")
    return ", ".join(parts)


def era_idx(e):
    return ERA_ORDER.index(e) if e in ERA_ORDER else 99


# ========================================================== global params ==

def gen_global_parameters(c: Ctx, out):
    rows = c.q("SELECT Name, Value FROM GlobalParameters ORDER BY Name")
    groups = defaultdict(list)
    for r in rows:
        prefix = r["Name"].split("_")[0]
        groups[prefix].append((r["Name"], r["Value"]))
    sections = []
    for prefix in sorted(groups):
        sections.append((prefix, table(["Parameter", "Value"], groups[prefix])))
    return write(out, "global-parameters.md", "Global Parameters",
                 "Every row of the `GlobalParameters` table after Base, Rise and Fall and Gathering Storm "
                 "overrides. Grouped by name prefix. Engine code reads these by name; meanings are "
                 "mostly evident from the name, and the narrative spec files cite the ones they use.",
                 sections)


# ============================================================== game setup ==

def gen_game_setup(c: Ctx, out):
    s = []
    rows = c.q("SELECT * FROM GameSpeeds ORDER BY CostMultiplier")
    turns = c.multi("SELECT GameSpeedType, MonthIncrement || ' months x ' || TurnsPerIncrement FROM GameSpeed_Turns")
    tot = {}
    for r in c.q("SELECT GameSpeedType, SUM(TurnsPerIncrement) t FROM GameSpeed_Turns GROUP BY 1"):
        tot[r[0]] = r[1]
    s.append(("Game speeds", table(
        ["Speed", "Cost multiplier %", "Total turns (calendar)", "Civic unlock max/min cost, drop/turn", "Calendar"],
        [(c.n(r["GameSpeedType"]), r["CostMultiplier"], tot.get(r["GameSpeedType"], ""),
          f"{r['CivicUnlockMaxCost']}/{r['CivicUnlockMinCost']}, {r['CivicUnlockPerTurnDrop']}",
          "; ".join(turns.get(r["GameSpeedType"], []))) for r in rows])))
    if c.has_table("GameSpeed_Scalings"):
        s.append(("Game speed scalings", table(
            ["Scaling", "Speed", "Type", "Default multiplier"],
            [tuple(r) for r in c.q("SELECT * FROM GameSpeed_Scalings")])))
        s.append(("Game speed durations", table(
            ["Scaling", "Turns on Standard", "Scaled turns"],
            [tuple(r) for r in c.q("SELECT * FROM GameSpeed_Durations")])))
    # Map sizes
    rows = c.q("SELECT m.*, x.CO2For1DegreeTempRise FROM Maps m LEFT JOIN Maps_XP2 x USING(MapSizeType) ORDER BY GridWidth*GridHeight")
    s.append(("Map sizes", table(
        ["Size", "Grid", "Default players", "Natural wonders", "Fog tiles per barbarian camp", "Target/estimated cities",
         "Research %", "Tech cost mod per city", "Policy cost mod per city", "Continents", "CO2 per 1 degree rise"],
        [(c.n(r["MapSizeType"]), f"{r['GridWidth']}x{r['GridHeight']}", r["DefaultPlayers"], r["NumNaturalWonders"],
          r["FogTilesPerBarbarianCamp"], f"{r['TargetNumCities']}/{r['EstimatedNumCities']}", r["ResearchPercent"],
          r["NumCitiesTechCostMod"], r["NumCitiesPolicyCostMod"], r["Continents"], r["CO2For1DegreeTempRise"])
         for r in rows])))
    gp = c.q("SELECT * FROM Map_GreatPersonClasses")
    if gp:
        s.append(("Map size limits on Great Person classes", table(
            ["Size", "Class", "Max in world"], [(c.n(r[0]), c.n(r[1]), r[2]) for r in gp])))
    # Difficulty
    diffs = [r[0] for r in c.q("SELECT DifficultyType FROM Difficulties")]
    order = ["DIFFICULTY_SETTLER", "DIFFICULTY_CHIEFTAIN", "DIFFICULTY_WARLORD", "DIFFICULTY_PRINCE",
             "DIFFICULTY_KING", "DIFFICULTY_EMPEROR", "DIFFICULTY_IMMORTAL", "DIFFICULTY_DEITY"]
    diffs = [d for d in order if d in diffs] + [d for d in diffs if d not in order]
    s.append(("Difficulty levels", "Order (index 0..7): " + ", ".join(c.n(d) for d in diffs) + ".\n"))
    mods = [r[0] for r in c.q("SELECT DISTINCT a.ModifierId FROM ModifierArguments a WHERE a.Type='LinearScaleFromDefaultHandicap'")]
    rows = []
    for m in mods:
        args = c.q("SELECT Name, Value, Extra, SecondExtra FROM ModifierArguments WHERE ModifierId=? AND Type='LinearScaleFromDefaultHandicap'", m)
        for a in args:
            rows.append((m, c.r.modifier(m), a["Name"], a["Value"], a["Extra"], a["SecondExtra"] or ""))
    s.append(("Difficulty-scaled modifiers (attached to every major civ)", table(
        ["Modifier", "Effect", "Argument", "Base value", "Change per difficulty step", "Cap / reference difficulty"], rows)
        + "\nArguments of type `LinearScaleFromDefaultHandicap` evaluate to `base + step x (difficulty index - default index)`; "
          "see the narrative spec (00-overview) for the resulting per-level numbers.\n"))
    rows = c.q("SELECT * FROM MajorStartingUnits ORDER BY Era, AiOnly, Unit")
    s.append(("Starting units (major civs)", table(
        ["Unit", "Start era", "Quantity", "AI only", "Min difficulty", "Extra per difficulty step", "District", "Not on start tile"],
        [(c.n(r["Unit"]), c.n(r["Era"]), r["Quantity"], yesno(r["AiOnly"]), c.n(r["MinDifficulty"]), r["DifficultyDelta"],
          c.n(r["District"]), yesno(r["NotStartTile"])) for r in rows])))
    rows = c.q("SELECT * FROM BonusMinorStartingUnits")
    s.append(("Starting units (city-states, bonus)", table(
        ["Unit", "Era", "Quantity", "Min difficulty", "Per difficulty step", "On district created", "District"],
        [(c.n(r["Unit"]), c.n(r["Era"]), r["Quantity"], c.n(r["MinDifficulty"]), r["DifficultyDelta"],
          yesno(r["OnDistrictCreated"]), c.n(r["District"])) for r in rows])))
    cols = [x[1] for x in c.db.execute("PRAGMA table_info(StartEras)")]
    rows = c.q("SELECT * FROM StartEras")
    s.append(("Advanced start eras", table(cols, [[num(v) if not isinstance(v, str) else c.n(v) if k.endswith("Type") else v
                                                     for k, v in zip(cols, r)] for r in rows])))
    s.append(("Starting buildings by start era", table(
        ["Building", "Era", "District", "Minor only", "Min difficulty"],
        [(c.n(r[0]), c.n(r[1]), c.n(r[2]), yesno(r[3]), c.n(r[4])) for r in c.q("SELECT * FROM StartingBuildings")])))
    s.append(("Scoring", table(["Line item", "Category", "Multiplier", "Scale by cost"] ,
        [(r["LineItemType"], c.n(r["Category"]), r["Multiplier"], yesno(r["ScaleByCost"])) for r in c.q("SELECT * FROM ScoringLineItems")])))
    s.append(("Victories", table(["Victory", "Requirement set", "Enabled by default", "Critical %"],
        [(c.n(r["VictoryType"]), c.r.requirement_set(r["RequirementSetId"]) or r["RequirementSetId"], yesno(r["EnabledByDefault"]),
          r["CriticalPercentage"]) for r in c.q("SELECT * FROM Victories")])))
    return write(out, "game-setup.md", "Game Setup: Speeds, Map Sizes, Difficulty, Start, Scoring", "", s)


# ======================================================= terrain & resources =

def gen_terrain(c: Ctx, out):
    s = []
    ty = c.multi("SELECT TerrainType, YieldType || ':' || YieldChange FROM Terrain_YieldChanges")

    def ys(lst):
        return ", ".join(f"+{v} {c.n(k)}" for k, v in (x.split(":") for x in lst))

    rows = c.q("SELECT * FROM Terrains")
    s.append(("Terrains", table(
        ["Terrain", "Yields", "Move cost", "Defense", "Appeal", "Sight mod / through", "Impassable", "Water/shallow", "Hills/Mountain"],
        [(c.n(r["TerrainType"]), ys(ty.get(r["TerrainType"], [])), r["MovementCost"], r["DefenseModifier"], r["Appeal"],
          f"{r['SightModifier']}/{r['SightThroughModifier']}", yesno(r["Impassable"]),
          f"{yesno(r['Water'])}/{yesno(r['ShallowWater'])}", f"{yesno(r['Hills'])}/{yesno(r['Mountain'])}") for r in rows])))
    fy = c.multi("SELECT FeatureType, YieldType || ':' || YieldChange FROM Feature_YieldChanges")
    fadj = c.multi("SELECT FeatureType, '+' || YieldChange || ' ' || YieldType FROM Feature_AdjacentYields")
    fvalid = c.multi("SELECT FeatureType, TerrainType FROM Feature_ValidTerrains")
    frem = c.multi("SELECT FeatureType, YieldType || ' ' || Yield FROM Feature_Removes")
    xp2 = {r[0]: r for r in c.q("SELECT * FROM Features_XP2")}
    rows = c.q("SELECT * FROM Features WHERE NaturalWonder=0")
    s.append(("Features", table(
        ["Feature", "Yields", "Move change", "Defense", "Appeal", "Removable / remove tech", "Harvest yields", "Fresh water",
         "Sight-blocking", "Valid terrains", "GS flags"],
        [(c.n(r["FeatureType"]), ys(fy.get(r["FeatureType"], [])), r["MovementChange"], r["DefenseModifier"], r["Appeal"],
          f"{yesno(r['Removable'])} {c.n(r['RemoveTech'])}".strip(),
          ", ".join(f"{c.n(a.split()[0])} {a.split()[1]}" for a in frem.get(r["FeatureType"], [])),
          yesno(r["AddsFreshWater"]), r["SightThroughModifier"],
          ", ".join(c.n(t) for t in fvalid.get(r["FeatureType"], [])),
          ("volcano " if r["FeatureType"] in xp2 and xp2[r["FeatureType"]]["Volcano"] else "")
          + ("district ok" if r["FeatureType"] in xp2 and xp2[r["FeatureType"]]["ValidDistrictPlacement"] else ""))
         for r in rows])))
    fmods = c.multi("SELECT FeatureType, ModifierId FROM FeatureModifiers") if c.has_table("FeatureModifiers") else {}
    rows = c.q("SELECT * FROM Features WHERE NaturalWonder=1")
    s.append(("Natural wonders", table(
        ["Natural wonder", "Tiles", "Yields", "Adjacent tile yields", "Impassable", "Appeal", "Doubles adjacent terrain yield",
         "Fresh water", "Valid terrains", "Modifiers"],
        [(c.n(r["FeatureType"]), r["Tiles"], ys(fy.get(r["FeatureType"], [])),
          ", ".join(c.n(x.split(" ")[1]).join(["", ""]) and (x.split(" ")[0] + " " + c.n(x.split(" ")[1])) for x in fadj.get(r["FeatureType"], [])),
          yesno(r["Impassable"]), r["Appeal"], yesno(r["DoubleAdjacentTerrainYield"]), yesno(r["AddsFreshWater"]),
          ", ".join(c.n(t) for t in fvalid.get(r["FeatureType"], [])),
          c.r.modifiers(fmods.get(r["FeatureType"], []))) for r in rows])))
    # Resources
    ry = c.multi("SELECT ResourceType, YieldType || ':' || YieldChange FROM Resource_YieldChanges")
    rvt = c.multi("SELECT ResourceType, TerrainType FROM Resource_ValidTerrains")
    rvf = c.multi("SELECT ResourceType, FeatureType FROM Resource_ValidFeatures")
    imp = c.multi("SELECT ResourceType, ImprovementType FROM Improvement_ValidResources")
    harv = {r[0]: r for r in c.q("SELECT * FROM Resource_Harvests")}
    cons = {r["ResourceType"]: r for r in c.q("SELECT * FROM Resource_Consumption")}
    rows = c.q("SELECT * FROM Resources ORDER BY ResourceClassType, ResourceType")
    for cls in ("RESOURCECLASS_BONUS", "RESOURCECLASS_LUXURY", "RESOURCECLASS_STRATEGIC", "RESOURCECLASS_ARTIFACT"):
        sub = [r for r in rows if r["ResourceClassType"] == cls]
        if not sub:
            continue
        body = table(
            ["Resource", "Yields", "Amenities", "Improvement", "Revealed by", "Valid terrain/feature", "Frequency/sea", "Harvest"],
            [(c.n(r["ResourceType"]), ys(ry.get(r["ResourceType"], [])), r["Happiness"] or "",
              ", ".join(c.n(i) for i in imp.get(r["ResourceType"], [])),
              c.n(r["PrereqTech"]) or c.n(r["PrereqCivic"]),
              ", ".join(dict.fromkeys([c.n(t) for t in rvt.get(r["ResourceType"], [])] + [c.n(f) for f in rvf.get(r["ResourceType"], [])])),
              f"{r['Frequency']}/{r['SeaFrequency']}",
              (f"{harv[r['ResourceType']]['Amount']} {c.n(harv[r['ResourceType']]['YieldType'])} ({c.n(harv[r['ResourceType']]['PrereqTech'])})"
               if r["ResourceType"] in harv else "")) for r in sub])
        s.append((c.n(cls).replace("Resourceclass ", "") + " resources" if cls not in c.n.names else c.n(cls), body))
    s.append(("Strategic resource accumulation and power [GS]", table(
        ["Resource", "Accumulates", "Base / improved extraction per turn", "Stockpile cap", "Power per unit", "CO2 per kWh", "Obsolete tech"],
        [(c.n(r["ResourceType"]), yesno(r["Accumulate"]), f"{r['BaseExtractionRate']}/{r['ImprovedExtractionRate']}",
          r["StockpileCap"], r["PowerProvided"], r["CO2perkWh"], c.n(r["ObsoleteTech"])) for r in cons.values()])))
    rows = c.q("SELECT r.*, x.BuildOnlyWithUnit, x.BuildWithUnitChargeCost, x.PrereqTech FROM Routes r LEFT JOIN Routes_XP2 x USING(RouteType)")
    rc = c.multi("SELECT RouteType, ResourceType || ' x' || BuildWithUnitCost FROM Route_ResourceCosts")
    s.append(("Routes", table(
        ["Route", "Movement cost", "Bridges", "Prereq era", "Prereq tech [GS]", "Only built by unit", "Charge cost", "Resource cost"],
        [(c.n(r["RouteType"]), r["MovementCost"], yesno(r["SupportsBridges"]), c.n(r["PrereqEra"]), c.n(r["PrereqTech"]),
          yesno(r["BuildOnlyWithUnit"]), r["BuildWithUnitChargeCost"],
          ", ".join(c.n(x.split(" ")[0]) + " " + x.split(" ")[1] for x in rc.get(r["RouteType"], []))) for r in rows])))
    s.append(("Resource distribution [map script inputs]", table(
        ["Continents", "Scarce", "Average", "Plentiful", "Percent adjusted"],
        [tuple(r) for r in c.q("SELECT * FROM Resource_Distribution")])))
    return write(out, "terrain-features-resources.md", "Terrain, Features, Natural Wonders, Resources, Routes", "", s)


# =========================================================== improvements ==

def gen_improvements(c: Ctx, out):
    s = []
    iy = c.multi("SELECT ImprovementType, '+' || YieldChange || ' ' || YieldType FROM Improvement_YieldChanges WHERE YieldChange != 0")
    vt = c.multi("SELECT ImprovementType, TerrainType FROM Improvement_ValidTerrains")
    vf = c.multi("SELECT ImprovementType, FeatureType FROM Improvement_ValidFeatures")
    vr = c.multi("SELECT ImprovementType, ResourceType FROM Improvement_ValidResources")
    bonus = c.multi("SELECT ImprovementType, '+' || BonusYieldChange || ' ' || YieldType || ' with ' || COALESCE(PrereqTech, PrereqCivic) FROM Improvement_BonusYieldChanges")
    adj = c.multi("SELECT ImprovementType, YieldChangeId FROM Improvement_Adjacencies")
    tour = c.multi("SELECT ImprovementType, TourismSource || ' x' || ScalingFactor || '% after ' || COALESCE(PrereqTech, PrereqCivic, '') FROM Improvement_Tourism")
    builders = c.multi("SELECT ImprovementType, UnitType FROM Improvement_ValidBuildUnits")
    mods = c.multi("SELECT ImprovementType, ModifierID FROM ImprovementModifiers")
    adjrows = {r["ID"]: r for r in c.q("SELECT * FROM Adjacency_YieldChanges")}
    xp2 = {r[0]: r for r in c.q("SELECT * FROM Improvements_XP2")}

    def ny(lst):
        out_ = []
        for x in lst:
            parts = x.split(" ")
            out_.append(" ".join([parts[0], c.n(parts[1])] + [c.n(p) for p in parts[2:]]))
        return ", ".join(out_)

    rows = c.q("SELECT * FROM Improvements ORDER BY TraitType IS NOT NULL, ImprovementType")
    body = []
    for r in rows:
        it = r["ImprovementType"]
        body.append((
            c.n(it), c.n(r["PrereqTech"]) or c.n(r["PrereqCivic"]), ny(iy.get(it, [])),
            ", ".join(dict.fromkeys([c.n(t) for t in vt.get(it, [])] + [c.n(f) for f in vf.get(it, [])])),
            ", ".join(c.n(x) for x in vr.get(it, [])),
            ny(bonus.get(it, [])),
            "; ".join(dict.fromkeys(adjacency_text(c, adjrows[a]) for a in adj.get(it, []) if a in adjrows)),
            num(r["Housing"]) + (f" (per {r['TilesRequired']} tiles)" if r["TilesRequired"] and r["TilesRequired"] > 1 else ""),
            r["Appeal"], r["DefenseModifier"] or "", yesno(r["GrantFortification"]), r["MinimumAppeal"] or "",
            ", ".join(c.n(u) for u in builders.get(it, [])),
            "; ".join(tour.get(it, [])),
            c.owner(r["TraitType"]),
            ("disaster-resistant " if it in xp2 and xp2[it]["DisasterResistant"] else "") +
            ("prevents drought" if it in xp2 and xp2[it]["PreventsDrought"] else ""),
            c.r.modifiers(mods.get(it, [])),
        ))
    s.append(("Improvements", table(
        ["Improvement", "Unlock", "Base yields", "Valid terrain/feature", "Valid resources", "Bonus yields", "Adjacency",
         "Housing", "Appeal", "Defense", "Fortify", "Min appeal", "Built by", "Tourism", "Unique to", "GS flags", "Modifiers"],
        body)))
    return write(out, "improvements.md", "Tile Improvements", "", s)


def adjacency_text(c: Ctx, a) -> str:
    src = []
    if a["OtherDistrictAdjacent"]:
        src.append("district")
    if a["AdjacentSeaResource"]:
        src.append("sea resource")
    if a["AdjacentTerrain"]:
        src.append(c.n(a["AdjacentTerrain"]))
    if a["AdjacentFeature"]:
        src.append(c.n(a["AdjacentFeature"]))
    if a["AdjacentRiver"]:
        src.append("river")
    if a["AdjacentWonder"]:
        src.append("wonder")
    if a["AdjacentNaturalWonder"]:
        src.append("natural wonder")
    if a["AdjacentImprovement"]:
        src.append(c.n(a["AdjacentImprovement"]))
    if a["AdjacentDistrict"]:
        src.append(c.n(a["AdjacentDistrict"]))
    if a["AdjacentResource"]:
        src.append("resource")
    if a["AdjacentResourceClass"] and a["AdjacentResourceClass"] != "NO_RESOURCECLASS":
        src.append(c.n(a["AdjacentResourceClass"]).replace("Resourceclass ", "") + " resource")
    if a["Self"]:
        src.append("self (own tile)")
    per = f"per {a['TilesRequired']} " if a["TilesRequired"] and a["TilesRequired"] > 1 else "per "
    cond = []
    if a["PrereqTech"]:
        cond.append("needs " + c.n(a["PrereqTech"]))
    if a["PrereqCivic"]:
        cond.append("needs " + c.n(a["PrereqCivic"]))
    if a["ObsoleteTech"]:
        cond.append("obsolete with " + c.n(a["ObsoleteTech"]))
    if a["ObsoleteCivic"]:
        cond.append("obsolete with " + c.n(a["ObsoleteCivic"]))
    amt = a["YieldChange"]
    return (f"{'+' if amt >= 0 else ''}{amt} {c.n(a['YieldType'])} {per}{'/'.join(src) or '?'}"
            + (f" ({', '.join(cond)})" if cond else ""))


# =============================================================== districts ==

def gen_districts(c: Ctx, out):
    s = []
    adj = c.multi("SELECT DistrictType, YieldChangeId FROM District_Adjacencies")
    adjrows = {r["ID"]: r for r in c.q("SELECT * FROM Adjacency_YieldChanges")}
    cit = c.multi("SELECT DistrictType, '+' || YieldChange || ' ' || YieldType FROM District_CitizenYieldChanges")
    gpp = c.multi("SELECT DistrictType, '+' || PointsPerTurn || ' ' || GreatPersonClassType FROM District_GreatPersonPoints")
    trade = defaultdict(list)
    for r in c.q("SELECT * FROM District_TradeRouteYields"):
        trade[r["DistrictType"]].append(f"{c.n(r['YieldType'])} {num(r['YieldChangeAsOrigin'])}/{num(r['YieldChangeAsDomesticDestination'])}/{num(r['YieldChangeAsInternationalDestination'])}")
    vt = c.multi("SELECT DistrictType, TerrainType FROM District_ValidTerrains")
    rf = c.multi("SELECT DistrictType, FeatureType FROM District_RequiredFeatures")
    mods = c.multi("SELECT DistrictType, ModifierId FROM DistrictModifiers")
    repl = {r[0]: r[1] for r in c.q("SELECT CivUniqueDistrictType, ReplacesDistrictType FROM DistrictReplaces")}
    xp2 = {r["DistrictType"]: r for r in c.q("SELECT * FROM Districts_XP2")}
    excl = c.multi("SELECT District, MutuallyExclusiveDistrict FROM MutuallyExclusiveDistricts")
    appeal_h = c.multi("SELECT DistrictType, 'appeal>=' || MinimumValue || ': +' || AppealChange FROM AppealHousingChanges")

    def ny(lst):
        out_ = []
        for x in lst:
            parts = x.split(" ")
            out_.append(" ".join([parts[0]] + [c.n(p) for p in parts[1:]]))
        return ", ".join(out_)

    rows = c.q("SELECT * FROM Districts ORDER BY TraitType IS NOT NULL, Cost")
    body, body2 = [], []
    for r in rows:
        d = r["DistrictType"]
        x = xp2.get(d)
        flags = []
        if r["OnePerCity"]:
            flags.append("one per city")
        if r["MaxPerPlayer"] and r["MaxPerPlayer"] > 0:
            flags.append(f"max {num(r['MaxPerPlayer'])} per player")
        if r["RequiresPlacement"] == 0:
            flags.append("no placement")
        if r["NoAdjacentCity"]:
            flags.append("not adjacent to City Center")
        if r["Aqueduct"]:
            flags.append("aqueduct rules")
        if r["Coast"]:
            flags.append("coast/lake")
        if r["AdjacentToLand"]:
            flags.append("adjacent to land")
        if r["InternalOnly"]:
            flags.append("internal")
        if x is not None:
            if x["OnePerRiver"]:
                flags.append("one per river")
            if x["PreventsFloods"]:
                flags.append("prevents floods")
            if x["PreventsDrought"]:
                flags.append("prevents drought")
            if x["Canal"]:
                flags.append("canal")
            if x["AttackRange"]:
                flags.append(f"attack range {x['AttackRange']}")
        if d in excl:
            flags.append("exclusive with " + ", ".join(c.n(e) for e in excl[d]))
        body.append((
            c.n(d), c.n(r["PrereqTech"]) or c.n(r["PrereqCivic"]), r["Cost"],
            f"{r['CostProgressionModel']} {r['CostProgressionParam1']}".replace("COST_PROGRESSION_", "").strip(),
            r["RequiresPopulation"] and "yes" or "", r["Maintenance"], r["HitPoints"] or "",
            r["Housing"] or "", r["Entertainment"] or "", r["Appeal"], r["CitizenSlots"] or "",
            ny(cit.get(d, [])), ny(gpp.get(d, [])), r["AirSlots"] or "",
            f"{c.n(r['PlunderType'])} {r['PlunderAmount']}".strip() if r["PlunderType"] not in (None, "NO_PLUNDER") else "",
            "; ".join(flags), c.n(repl[d]) if d in repl else "", c.owner(r["TraitType"])))
        body2.append((c.n(d),
                       "; ".join(dict.fromkeys(adjacency_text(c, adjrows[a]) for a in adj.get(d, []) if a in adjrows)),
                       ", ".join(dict.fromkeys(c.n(t) for t in vt.get(d, []))) + (" | requires " + ", ".join(c.n(f) for f in rf[d]) if d in rf else ""),
                       "; ".join(trade.get(d, [])),
                       "; ".join(appeal_h.get(d, [])),
                       c.r.modifiers(mods.get(d, []))))
    s.append(("District stats", table(
        ["District", "Unlock", "Base cost", "Cost progression", "Needs pop", "Maintenance", "HP", "Housing", "Amenity",
         "Appeal", "Citizen slots", "Specialist yields", "GPP per turn", "Air slots", "Pillage", "Placement/flags", "Replaces", "Unique to"],
        body)))
    s.append(("District adjacency, placement, trade-route yields and modifiers", table(
        ["District", "Adjacency rules", "Valid terrain", "Trade route yields (as origin / domestic dest. / international dest.)",
         "Appeal housing", "Modifiers"], body2)))
    s.append(("Appeal-based district yields", table(
        ["District/Building", "Yield", "Change", "Min appeal", "Max", "Unimproved only"],
        [(c.n(r["DistrictType"] or r["BuildingType"]), c.n(r["YieldType"]), r["YieldChange"], r["MinimumValue"],
          r["MaximumValue"], yesno(r["Unimproved"])) for r in c.q("SELECT * FROM Adjacent_AppealYieldChanges")])))
    s.append(("Districts that copy adjacency into other yields / build-charge production", table(
        ["District", "Unit", "% production per charge"],
        [(c.n(r[0]), c.n(r[1]), r[2]) for r in c.q("SELECT * FROM District_BuildChargeProductions")])))
    return write(out, "districts.md", "Districts",
                 "Cost progression: `COST_PROGRESSION_GAME_PROGRESS` with param P means cost = base x (1 + P/100 x progress) "
                 "where progress is the share of the tech or civic tree completed (engine). Adjacency rules list each "
                 "`Adjacency_YieldChanges` row; 'per 2 X' rows round down.", s)


# =============================================================== buildings ==

def building_rows(c: Ctx, wonders: bool):
    by = c.multi("SELECT BuildingType, '+' || YieldChange || ' ' || YieldType FROM Building_YieldChanges")
    byp = c.multi("SELECT BuildingType, '+' || YieldChange || ' ' || YieldType FROM Building_YieldChangesBonusWithPower")
    cy = c.multi("SELECT BuildingType, '+' || YieldChange || ' ' || YieldType FROM Building_CitizenYieldChanges")
    gp = c.multi("SELECT BuildingType, '+' || PointsPerTurn || ' ' || GreatPersonClassType FROM Building_GreatPersonPoints")
    gw = c.multi("SELECT BuildingType, NumSlots || ' ' || GreatWorkSlotType FROM Building_GreatWorks")
    pre = c.multi("SELECT Building, PrereqBuilding FROM BuildingPrereqs")
    excl = c.multi("SELECT Building, MutuallyExclusiveBuilding FROM MutuallyExclusiveBuildings")
    mods = c.multi("SELECT BuildingType, ModifierId FROM BuildingModifiers")
    vt = c.multi("SELECT BuildingType, TerrainType FROM Building_ValidTerrains")
    vf = c.multi("SELECT BuildingType, FeatureType FROM Building_ValidFeatures")
    rf = c.multi("SELECT BuildingType, FeatureType FROM Building_RequiredFeatures")
    repl = {r[0]: r[1] for r in c.q("SELECT * FROM BuildingReplaces")}
    xp2 = {r["BuildingType"]: r for r in c.q("SELECT * FROM Buildings_XP2")}
    tb = {r[0]: r[1] for r in c.q("SELECT * FROM Building_TourismBombs_XP2")}

    def ny(lst):
        out_ = []
        for x in lst:
            parts = x.split(" ")
            out_.append(" ".join([parts[0]] + [c.n(p).replace("Greatworkslot ", "") for p in parts[1:]]))
        return ", ".join(out_)

    rows = c.q("SELECT * FROM Buildings WHERE IsWonder=? ORDER BY PrereqDistrict, Cost", 1 if wonders else 0)
    out = []
    for r in rows:
        b = r["BuildingType"]
        x = xp2.get(b)
        place = []
        if r["RequiresRiver"] or r["RequiresAdjacentRiver"]:
            place.append("river")
        if r["Coast"]:
            place.append("coast")
        if r["MustBeLake"]:
            place.append("lake")
        if r["MustNotBeLake"]:
            place.append("not lake")
        if r["AdjacentDistrict"]:
            place.append("adjacent to " + c.n(r["AdjacentDistrict"]))
        if r["AdjacentResource"]:
            place.append("adjacent to " + c.n(r["AdjacentResource"]))
        if r["AdjacentImprovement"]:
            place.append("adjacent to " + c.n(r["AdjacentImprovement"]))
        if r["AdjacentToMountain"]:
            place.append("adjacent to mountain")
        if r["AdjacentCapital"]:
            place.append("adjacent to capital")
        if r["MustBeAdjacentLand"]:
            place.append("adjacent to land")
        if r["CityAdjacentTerrain"]:
            place.append("city next to " + c.n(r["CityAdjacentTerrain"]))
        if b in vt:
            place.append("on " + "/".join(dict.fromkeys(c.n(t) for t in vt[b])))
        if b in vf:
            place.append("on " + "/".join(c.n(t) for t in vf[b]))
        if b in rf:
            place.append("requires " + "/".join(c.n(t) for t in rf[b]))
        power = ""
        if x is not None:
            if x["RequiredPower"]:
                power = f"needs {x['RequiredPower']} power"
            if x["ResourceTypeConvertedToPower"]:
                power += f" burns {c.n(x['ResourceTypeConvertedToPower'])}"
            for flag in ("PreventsFloods", "PreventsDrought", "BlocksCoastalFlooding", "Bridge", "CanalWonder", "NuclearReactor"):
                if x[flag]:
                    power += f" {flag}"
            if x["EntertainmentBonusWithPower"]:
                power += f" +{x['EntertainmentBonusWithPower']} amenity when powered"
        out.append(dict(
            name=c.n(b), district=c.n(r["PrereqDistrict"]), unlock=c.n(r["PrereqTech"]) or c.n(r["PrereqCivic"]),
            cost=r["Cost"], maint=r["Maintenance"], yields=ny(by.get(b, [])),
            power_yields=ny(byp.get(b, [])), housing=r["Housing"] or "", amen=r["Entertainment"] or "",
            citizens=r["CitizenSlots"] or "", cityields=ny(cy.get(b, [])), gpp=ny(gp.get(b, [])),
            gw=ny(gw.get(b, [])), prereq=", ".join(c.n(p) for p in pre.get(b, [])),
            excl=", ".join(c.n(p) for p in excl.get(b, [])), regional=r["RegionalRange"] or "",
            defense=(f"{r['OuterDefenseHitPoints']} HP / +{r['OuterDefenseStrength']}" if r["OuterDefenseHitPoints"] else ""),
            purchase=c.n(r["PurchaseYield"]), place="; ".join(place), power=power.strip(),
            era=c.n(r["ObsoleteEra"]), replaces=c.n(repl.get(b)), trait=c.owner(r["TraitType"]),
            tourism_bomb=tb.get(b, ""),
            mods=c.r.modifiers(mods.get(b, [])), raw=r))
    return out


def gen_buildings(c: Ctx, out):
    rows = building_rows(c, False)
    s = [("Buildings", table(
        ["Building", "District", "Unlock", "Cost", "Maint.", "Yields", "Extra when powered", "Housing", "Amenity", "Citizen slots",
         "Specialist yields", "GPP", "Great Work slots", "Requires", "Exclusive with", "Regional range", "Defense",
         "Purchase", "Placement", "Power [GS]", "Replaces", "Unique to", "Modifiers"],
        [(b["name"], b["district"], b["unlock"], b["cost"], b["maint"], b["yields"], b["power_yields"], b["housing"],
          b["amen"], b["citizens"], b["cityields"], b["gpp"], b["gw"], b["prereq"], b["excl"], b["regional"], b["defense"],
          b["purchase"], b["place"], b["power"], b["replaces"], b["trait"], b["mods"]) for b in rows]))]
    gw = c.q("SELECT * FROM Building_GreatWorks")
    s.append(("Great Work slots and theming", table(
        ["Building", "Slot type", "Slots", "Theming: unique person / same object / unique civs / same eras", "Theming yield x / tourism x"],
        [(c.n(r["BuildingType"]), c.n(r["GreatWorkSlotType"]).replace("Greatworkslot ", ""), r["NumSlots"],
          f"{yesno(r['ThemingUniquePerson'])}/{yesno(r['ThemingSameObjectType'])}/{yesno(r['ThemingUniqueCivs'])}/{yesno(r['ThemingSameEras'])}",
          f"{r['ThemingYieldMultiplier']}/{r['ThemingTourismMultiplier']}") for r in gw])))
    return write(out, "buildings.md", "Buildings (non-wonder)",
                 "Yields are flat per-building changes; percentage effects and conditional yields appear under Modifiers.", s)


def gen_wonders(c: Ctx, out):
    rows = building_rows(c, True)
    s = [("World wonders", table(
        ["Wonder", "Unlock", "Era", "Cost", "Yields", "Housing", "Amenity", "Regional range", "GPP", "Great Work slots", "Placement",
         "Flags [GS]", "Effects (modifiers)"],
        [(b["name"], b["unlock"], era_of_unlock(c, b["raw"]), b["cost"], b["yields"], b["housing"], b["amen"], b["regional"], b["gpp"], b["gw"],
          b["place"] + (f"; {b['district']}" if b["district"] else ""), b["power"], b["mods"]) for b in rows]))]
    return write(out, "wonders.md", "World Wonders", "", s)


def era_of_unlock(c: Ctx, r):
    if r["PrereqTech"]:
        e = c.q("SELECT EraType FROM Technologies WHERE TechnologyType=?", r["PrereqTech"])
    elif r["PrereqCivic"]:
        e = c.q("SELECT EraType FROM Civics WHERE CivicType=?", r["PrereqCivic"])
    else:
        return ""
    return c.n(e[0][0]) if e else ""


# ==================================================================== units ==

def gen_units(c: Ctx, out):
    s = []
    up = c.multi("SELECT Unit, UpgradeUnit FROM UnitUpgrades")
    repl = {r[0]: r[1] for r in c.q("SELECT * FROM UnitReplaces")}
    xp2 = {r["UnitType"]: r for r in c.q("SELECT * FROM Units_XP2")}
    tags = c.multi("SELECT Type, Tag FROM TypeTags WHERE Type LIKE 'UNIT_%'")
    abil_by_tag = c.multi("SELECT t.Tag, t.Type FROM TypeTags t JOIN UnitAbilities a ON a.UnitAbilityType=t.Type WHERE a.Inactive=0")
    bprereq = c.multi("SELECT Unit, PrereqBuilding FROM Unit_BuildingPrereqs")
    rows = c.q("SELECT * FROM Units ORDER BY Domain, PromotionClass, Cost")
    body = []
    for r in rows:
        u = r["UnitType"]
        x = xp2.get(u)
        res = ""
        if r["StrategicResource"]:
            res = c.n(r["StrategicResource"])
            if x is not None and x["ResourceCost"]:
                res += f" {x['ResourceCost']}"
        maint_res = ""
        if x is not None and x["ResourceMaintenanceType"]:
            maint_res = f"{x['ResourceMaintenanceAmount']} {c.n(x['ResourceMaintenanceType'])}/turn"
        abilities = sorted({c.n(a) for t in tags.get(u, []) for a in abil_by_tag.get(t, [])})
        body.append((
            c.n(u), c.n(r["PromotionClass"]) or ("civilian" if not r["Combat"] else ""), c.n(r["Domain"]).replace("Domain ", ""),
            c.n(r["PrereqTech"]) or c.n(r["PrereqCivic"]), r["Cost"],
            f"{r['CostProgressionModel']} {r['CostProgressionParam1']}".replace("COST_PROGRESSION_", "") if r["CostProgressionModel"] not in (None, "NO_COST_PROGRESSION") else "",
            r["Maintenance"], r["Combat"] or "", r["RangedCombat"] or "", r["Bombard"] or "", r["Range"] or "",
            r["AntiAirCombat"] or "", r["BaseMoves"], r["BaseSightRange"], res, maint_res,
            ", ".join(c.n(v) for v in up.get(u, [])),
            c.n(r["ObsoleteTech"]) or c.n(r["ObsoleteCivic"]),
            c.n(r["MandatoryObsoleteTech"]) or c.n(r["MandatoryObsoleteCivic"]),
            c.n(r["PurchaseYield"]), " ".join(filter(None, [
                f"charges {r['BuildCharges']}" if r["BuildCharges"] else "",
                f"spread {r['SpreadCharges']}" if r["SpreadCharges"] else "",
                f"religious str {r['ReligiousStrength']}" if r["ReligiousStrength"] else "",
                f"heal charges {r['ReligiousHealCharges']}" if r["ReligiousHealCharges"] else "",
                f"park {r['ParkCharges']}" if r["ParkCharges"] else "",
                f"disaster {r['DisasterCharges']}" if r["DisasterCharges"] else "",
                f"pop cost {r['PopulationCost']}" if r["PopulationCost"] else "",
                f"needs pop {r['PrereqPopulation']}" if r["PrereqPopulation"] else "",
                "found city" if r["FoundCity"] else "", "found religion" if r["FoundReligion"] else "",
                "trade route" if r["MakeTradeRoute"] else "", "spy" if r["Spy"] else "",
                f"evict {r['ReligionEvictPercent']}%" if r["ReligionEvictPercent"] else "",
                "no ZOC" if not r["ZoneOfControl"] and r["Combat"] else "",
                f"district {c.n(r['PrereqDistrict'])}" if r["PrereqDistrict"] else "",
                "needs " + "/".join(c.n(b) for b in bprereq[u]) if u in bprereq else "",
                "must purchase" if r["MustPurchase"] else "",
                f"tourism bomb {x['TourismBomb']}" if x is not None and x["TourismBomb"] else "",
            ])), ", ".join(abilities), c.n(repl.get(u)), c.owner(r["TraitType"])))
    s.append(("Units", table(
        ["Unit", "Class", "Domain", "Unlock", "Cost", "Cost progression", "Gold maint.", "CS", "RS", "Bombard", "Range", "Anti-air",
         "Moves", "Sight", "Strategic cost [GS]", "Resource maint. [GS]", "Upgrades to", "Obsolete (can't build)",
         "Forced obsolete", "Purchase", "Special", "Innate abilities (via class tags)", "Replaces", "Unique to"], body)))
    abil = c.q("SELECT * FROM UnitAbilities ORDER BY UnitAbilityType")
    am = c.multi("SELECT UnitAbilityType, ModifierId FROM UnitAbilityModifiers")
    tagged = c.multi("SELECT Type, Tag FROM TypeTags WHERE Type LIKE 'ABILITY_%'")
    s.append(("Unit abilities", table(
        ["Ability", "Applies to class tags", "Inactive by default", "Effects"],
        [(c.n(a["UnitAbilityType"]), ", ".join(t.replace("CLASS_", "").lower() for t in tagged.get(a["UnitAbilityType"], [])),
          yesno(a["Inactive"]), c.r.modifiers(am.get(a["UnitAbilityType"], []))) for a in abil])))
    s.append(("Unit capture results", table(["Captured", "Becomes"], [(c.n(a), c.n(b)) for a, b in c.q("SELECT * FROM UnitCaptures")])))
    s.append(("Rock Band results [GS]", table(
        ["Result", "Album sales", "Tourism bomb", "Extra promotion", "Dies", "Gains level", "Base probability", "Stars"],
        [(c.n(r["ResultType"]), r["AlbumSales"], r["TourismBomb"], yesno(r["ExtraPromotion"]), yesno(r["Dies"]), yesno(r["GainsLevel"]),
          r["BaseProbability"], r["PerformanceStars"]) for r in c.q("SELECT * FROM Unit_RockbandResults_XP2")])))
    w = c.q("SELECT * FROM WMDs")
    s.append(("Weapons of mass destruction", table(
        ["Weapon", "Blast radius", "Fallout turns", "Affects population", "ICBM range", "Maintenance"],
        [(c.n(r["WeaponType"]), r["BlastRadius"], r["FalloutDuration"], r["AffectPopulation"], r["ICBMStrikeRange"], r["Maintenance"]) for r in w])))
    return write(out, "units.md", "Units", "CS = melee combat strength, RS = ranged strength. Costs are Standard speed.", s)


def gen_promotions(c: Ctx, out):
    s = []
    pre = c.multi("SELECT UnitPromotion, PrereqUnitPromotion FROM UnitPromotionPrereqs")
    mods = c.multi("SELECT UnitPromotionType, ModifierId FROM UnitPromotionModifiers")
    rows = c.q("SELECT * FROM UnitPromotions ORDER BY PromotionClass, Level, Column")
    by_class = defaultdict(list)
    for r in rows:
        by_class[r["PromotionClass"]].append(r)
    for cls, lst in by_class.items():
        s.append((c.n(cls), table(
            ["Promotion", "Tier", "Column", "Requires (any)", "Effect"],
            [(c.n(r["UnitPromotionType"]), r["Level"], r["Column"], ", ".join(c.n(p) for p in pre.get(r["UnitPromotionType"], [])),
              c.r.modifiers(mods.get(r["UnitPromotionType"], []))) for r in lst])))
    return write(out, "promotions.md", "Unit Promotions",
                 "Promotion XP thresholds and healing on promotion are engine/GlobalParameters values; see global-parameters.md "
                 "(EXPERIENCE_*). Tier = Level column; a promotion needs any one listed prerequisite.", s)


# ============================================================ techs/civics ==

def boost_text(c: Ctx, b) -> str:
    cls = b["BoostClass"]
    u1, u2 = c.n(b["Unit1Type"]), c.n(b["Unit2Type"])
    bld, imp, dist, res = c.n(b["BuildingType"]), c.n(b["ImprovementType"]), c.n(b["DistrictType"]), c.n(b["ResourceType"])
    nitems = b["NumItems"]
    def pl(word, k):
        if not word:
            return f"{k or 1} items"
        if k and k > 1:
            return f"{k} {word[:-1]}ies" if word.endswith("y") and word[-2:-1] not in "aeiou" else f"{k} {word}s"
        return f"a {word}" if word[0].lower() not in "aeiou" else f"an {word}"
    t = {
        "BOOST_TRIGGER_NUM_IMPROVED_TILES": f"improve {nitems} tiles",
        "BOOST_TRIGGER_DISCOVER_CONTINENT": "discover a second continent" if not nitems else f"discover {nitems} continents",
        "BOOST_TRIGGER_CLEAR_CAMP": "clear a barbarian camp",
        "BOOST_TRIGGER_HAVE_X_UNIQUE_SPECIALTY_DISTRICTS": f"have {nitems} different specialty districts",
        "BOOST_TRIGGER_EMPIRE_POPULATION": f"reach {nitems} total population",
        "BOOST_TRIGGER_CREATE_PANTHEON": "found a pantheon",
        "BOOST_TRIGGER_RESEARCH_TECH": f"research {c.n(b['BoostingTechType'])}",
        "BOOST_TRIGGER_CULTURVATE_CIVIC": f"complete the civic {c.n(b['BoostingCivicType'])}",
        "BOOST_TRIGGER_MEET_X_CITY_STATES": f"meet {nitems} city-states",
        "BOOST_TRIGGER_HAVE_X_WONDERS": f"build {pl('wonder', nitems)}",
        "BOOST_TRIGGER_HAVE_X_DISTRICTS": f"build {pl(dist or 'district', nitems)}",
        "BOOST_TRIGGER_RECEIVE_DOW": "be the target of a war declaration",
        "BOOST_TRIGGER_FOUND_RELIGION": "found a religion",
        "BOOST_TRIGGER_KILL_WITH": f"kill a unit with a {u1}",
        "BOOST_TRIGGER_KILL_SPECIFIC_UNIT": f"kill a {u1}",
        "BOOST_TRIGGER_HAVE_X_IMPROVEMENTS": f"build {pl(imp, nitems)}" + (" on a resource" if b["RequiresResource"] else ""),
        "BOOST_TRIGGER_CITY_POPULATION": f"grow a city to {nitems} population",
        "BOOST_TRIGGER_HAVE_X_LAND_UNITS": f"have {nitems} land combat units",
        "BOOST_TRIGGER_MAINTAIN_X_TRADE_ROUTES": f"have {pl('trade route', nitems)}",
        "BOOST_TRIGGER_HAVE_X_BUILDINGS": f"build {pl(bld, nitems)}",
        "BOOST_TRIGGER_CONSTRUCT_BUILDING": f"build a {bld}",
        "BOOST_TRIGGER_OWN_X_UNITS_OF_TYPE": f"own {pl(u1, nitems)}" + (f" and {u2}" if u2 else ""),
        "BOOST_TRIGGER_TRAIN_UNIT": f"train a {u1}",
        "BOOST_TRIGGER_HAVE_AN_ALLIANCE": "have an alliance",
        "BOOST_TRIGGER_HAVE_ALLIANCE_LEVEL_X": f"have a level {nitems} alliance",
        "BOOST_TRIGGER_HAVE_X_CITIES_FOLLOWING_YOUR_RELIGION": f"have {nitems} cities following your religion",
        "BOOST_TRIGGER_HAVE_X_GREAT_PEOPLE": f"earn {nitems} Great People",
        "BOOST_TRIGGER_DOW_CASUS_BELLI": "declare war using a casus belli",
        "BOOST_TRIGGER_DISTRICT_APPEAL_LEVEL_MINIMUM_X": f"have a {dist} with appeal {nitems}+",
        "BOOST_TRIGGER_HAVE_X_CORPS": f"have {nitems} corps",
        "BOOST_TRIGGER_HAVE_X_ARMIES": f"have {nitems} armies",
        "BOOST_TRIGGER_HAVE_X_THEMED_BUILDINGS": f"have {pl('themed building', nitems)}",
        "BOOST_TRIGGER_AIRBASE_FOREIGN_CONTINENT": "build an aerodrome/airstrip on a foreign continent",
        "BOOST_TRIGGER_SETTLE_COAST": "found a coastal city",
        "BOOST_TRIGGER_FIND_NATURAL_WONDER": "discover a natural wonder",
        "BOOST_TRIGGER_MEET_CIV": "meet another civilization",
        "BOOST_TRIGGER_NUM_BARBS_KILLED": f"kill {nitems} barbarians",
        "BOOST_TRIGGER_IMPROVE_SPECIFIC_RESOURCE": f"improve {res or 'a resource'}" + (f" ({nitems})" if nitems and nitems > 1 else ""),
        "BOOST_TRIGGER_HAVE_GOVERNMENT_TIER": f"adopt a {c.n(b['GovernmentTierType'])} government",
        "BOOST_TRIGGER_HAVE_BUILDING_MOUNTAIN": f"build a {bld} next to a mountain",
        "BOOST_TRIGGER_HAVE_WONDER_PAST_X_ERA": "build a wonder of a later era",
        "BOOST_TRIGGER_HAVE_UNIT_AND_IMPROVEMENT": f"have a {u1} and a {imp}",
        "BOOST_TRIGGER_CREATED_NATIONAL_PARK": "create a National Park",
        "BOOST_TRIGGER_ARTIFACT_EXTRACTED": "extract an artifact",
        "BOOST_TRIGGER_NONE_LATE_GAME_CRITICAL_TECH": "none (only via Great Scientist / spy / effects)",
    }.get(cls)
    if t is None:
        t = (cls or "").replace("BOOST_TRIGGER_", "").replace("_", " ").lower()
    if b["RequirementSetId"]:
        t += f" [{c.r.requirement_set(b['RequirementSetId'])}]"
    if b["GovernmentSlotType"]:
        t += f" (slot {c.n(b['GovernmentSlotType'])})"
    return t


def unlocks_index(c: Ctx, col: str):
    """Map tech/civic -> list of things it unlocks."""
    out = defaultdict(list)
    queries = [
        ("Units", "UnitType", "unit"), ("Buildings", "BuildingType", "building"), ("Districts", "DistrictType", "district"),
        ("Improvements", "ImprovementType", "improvement"), ("Projects", "ProjectType", "project"),
        ("Policies", "PolicyType", "policy"), ("Governments", "GovernmentType", "government"),
        ("Resources", "ResourceType", "reveals"),
    ]
    for t, key, label in queries:
        cols = [x[1] for x in c.db.execute(f"PRAGMA table_info({t})")]
        pc = "PrereqTech" if col == "tech" else "PrereqCivic"
        if pc not in cols:
            continue
        extra = " AND TraitType IS NULL" if "TraitType" in cols else ""
        for r in c.q(f"SELECT {key}, {pc} FROM {t} WHERE {pc} IS NOT NULL{extra}"):
            out[r[1]].append(f"{c.n(r[0])}" + (" (policy)" if label == "policy" else " (revealed)" if label == "reveals" else ""))
    return out


def gen_tech(c: Ctx, out):
    unl = unlocks_index(c, "tech")
    pre = c.multi("SELECT Technology, PrereqTech FROM TechnologyPrereqs")
    boosts = {r["TechnologyType"]: r for r in c.q("SELECT * FROM Boosts WHERE TechnologyType IS NOT NULL")}
    mods = c.multi("SELECT TechnologyType, ModifierId FROM TechnologyModifiers")
    rows = sorted(c.q("SELECT * FROM Technologies"), key=lambda r: (era_idx(r["EraType"]), r["Cost"], r["UITreeRow"] or 0))
    s = []
    for era in ERA_ORDER:
        lst = [r for r in rows if r["EraType"] == era]
        if not lst:
            continue
        s.append((c.n(era), table(
            ["Technology", "Cost", "Prerequisites", "Boost %", "Boost condition", "Unlocks", "Other effects"],
            [(c.n(r["TechnologyType"]), r["Cost"], ", ".join(c.n(p) for p in pre.get(r["TechnologyType"], [])),
              boosts[r["TechnologyType"]]["Boost"] if r["TechnologyType"] in boosts else "",
              boost_text(c, boosts[r["TechnologyType"]]) if r["TechnologyType"] in boosts else "",
              ", ".join(unl.get(r["TechnologyType"], [])) + (f"; embark {c.n(r['EmbarkUnitType']) or 'all'}" if r["EmbarkAll"] or r["EmbarkUnitType"] else ""),
              c.r.modifiers(mods.get(r["TechnologyType"], [])) + (" (repeatable)" if r["Repeatable"] else ""))
             for r in lst])))
    rc = c.q("SELECT * FROM TechnologyRandomCosts")
    if rc:
        s.append(("Tech shuffle / random costs (Tree Randomizer data, kept for reference)", table(["Tech", "Cost"], [(c.n(a), b) for a, b in rc])))
    return write(out, "technologies.md", "Technologies",
                 "Costs are Standard speed (multiply by game-speed CostMultiplier). Unlock lists exclude civ-unique items.", s)


def gen_civics(c: Ctx, out):
    unl = unlocks_index(c, "civic")
    pre = c.multi("SELECT Civic, PrereqCivic FROM CivicPrereqs")
    boosts = {r["CivicType"]: r for r in c.q("SELECT * FROM Boosts WHERE CivicType IS NOT NULL")}
    mods = c.multi("SELECT CivicType, ModifierId FROM CivicModifiers")
    rows = sorted(c.q("SELECT * FROM Civics"), key=lambda r: (era_idx(r["EraType"]), r["Cost"], r["UITreeRow"] or 0))
    s = []
    for era in ERA_ORDER:
        lst = [r for r in rows if r["EraType"] == era]
        if not lst:
            continue
        s.append((c.n(era), table(
            ["Civic", "Cost", "Prerequisites", "Boost %", "Boost condition", "Unlocks", "Other effects (envoys, governor titles, slots...)"],
            [(c.n(r["CivicType"]), r["Cost"], ", ".join(c.n(p) for p in pre.get(r["CivicType"], [])),
              boosts[r["CivicType"]]["Boost"] if r["CivicType"] in boosts else "",
              boost_text(c, boosts[r["CivicType"]]) if r["CivicType"] in boosts else "",
              ", ".join(unl.get(r["CivicType"], [])),
              c.r.modifiers(mods.get(r["CivicType"], [])) + (" (repeatable)" if r["Repeatable"] else ""))
             for r in lst])))
    return write(out, "civics.md", "Civics", "Costs are Standard speed. Unlock lists exclude civ-unique items.", s)


# ===================================================== governments/policies ==

def gen_governments(c: Ctx, out):
    s = []
    slots = defaultdict(dict)
    for r in c.q("SELECT * FROM Government_SlotCounts"):
        slots[r["GovernmentType"]][r["GovernmentSlotType"]] = r["NumSlots"]
    gm = c.multi("SELECT GovernmentType, ModifierId FROM GovernmentModifiers")
    favor = {r[0]: r[1] for r in c.q("SELECT * FROM Governments_XP2")}
    rows = c.q("SELECT * FROM Governments")
    st = ["SLOT_MILITARY", "SLOT_ECONOMIC", "SLOT_DIPLOMATIC", "SLOT_WILDCARD", "SLOT_GREAT_PERSON"]
    s.append(("Governments", table(
        ["Government", "Unlock", "Tier", "Military", "Economic", "Diplomatic", "Wildcard", "Great Person", "Influence pts/turn",
         "Influence threshold", "Envoys per threshold", "Favor/turn [GS]", "Inherent effects"],
        [(c.n(r["GovernmentType"]), c.n(r["PrereqCivic"]), c.n(r["Tier"]),
          *[slots[r["GovernmentType"]].get(x, 0) for x in st],
          r["InfluencePointsPerTurn"], r["InfluencePointsThreshold"], r["InfluenceTokensPerThreshold"],
          favor.get(r["GovernmentType"], ""), c.r.modifiers(gm.get(r["GovernmentType"], []))) for r in rows])))
    pm = c.multi("SELECT PolicyType, ModifierId FROM PolicyModifiers")
    obs = c.multi("SELECT PolicyType, ObsoletePolicy FROM ObsoletePolicies")
    xp1 = {r["PolicyType"]: r for r in c.q("SELECT * FROM Policies_XP1")}
    excl = c.multi("SELECT PolicyType, GovernmentType FROM Policy_GovernmentExclusives_XP2")
    rows = c.q("SELECT * FROM Policies ORDER BY GovernmentSlotType, PolicyType")
    for slot in st:
        lst = [r for r in rows if r["GovernmentSlotType"] == slot]
        if not lst:
            continue
        s.append((c.n(slot) + " policies", table(
            ["Policy", "Unlock", "Obsoleted by", "Age requirement [R&F]", "Government-exclusive [GS]", "Effects"],
            [(c.n(r["PolicyType"]), c.n(r["PrereqCivic"]) or c.n(r["PrereqTech"]) or ("government" if r["RequiresGovernmentUnlock"] else ""),
              ", ".join(c.n(o) for o in obs.get(r["PolicyType"], [])),
              age_req(c, xp1.get(r["PolicyType"])), ", ".join(c.n(g) for g in excl.get(r["PolicyType"], [])),
              c.r.modifiers(pm.get(r["PolicyType"], []))) for r in lst])))
    s.append(("Policy slot types", table(["Slot", "Accepts any policy"], [(c.n(r[0]), yesno(r[2])) for r in c.q("SELECT * FROM GovernmentSlots")])))
    return write(out, "governments-policies.md", "Governments and Policy Cards", "", s)


def age_req(c, r):
    if r is None:
        return ""
    parts = []
    if r["RequiresDarkAge"]:
        parts.append("Dark Age")
    if r["RequiresGoldenAge"]:
        parts.append("Golden Age")
    if r["MinimumGameEra"] or r["MaximumGameEra"]:
        parts.append(f"{c.n(r['MinimumGameEra'])}-{c.n(r['MaximumGameEra'])}")
    return " ".join(parts)


# ================================================================ religion ==

def gen_religion(c: Ctx, out):
    s = []
    bm = c.multi("SELECT BeliefType, ModifierID FROM BeliefModifiers")
    s.append(("Belief classes", table(["Class", "Max in religion", "Adoption order"],
        [(c.n(r["BeliefClassType"]), r["MaxInReligion"], r["AdoptionOrder"]) for r in c.q("SELECT * FROM BeliefClasses")])))
    for cls in [r[0] for r in c.q("SELECT BeliefClassType FROM BeliefClasses ORDER BY AdoptionOrder")]:
        rows = c.q("SELECT * FROM Beliefs WHERE BeliefClassType=? ORDER BY BeliefType", cls)
        s.append((c.n(cls), table(["Belief", "Effects"],
                                  [(c.n(r["BeliefType"]), c.r.modifiers(bm.get(r["BeliefType"], []))) for r in rows])))
    s.append(("Religions", table(["Religion", "Pantheon row"], [(c.n(r["ReligionType"]), yesno(r["Pantheon"])) for r in c.q("SELECT * FROM Religions")])))
    s.append(("Leader favored religions (AI)", table(["Leader", "Religion"],
        [(c.n(r["LeaderType"]), c.n(r["ReligionType"])) for r in c.q("SELECT * FROM FavoredReligions")])))
    rel_units = c.q("SELECT UnitType, Cost, BaseMoves, ReligiousStrength, SpreadCharges, ReligiousHealCharges, ReligionEvictPercent, PrereqDistrict FROM Units WHERE ReligiousStrength>0 OR SpreadCharges>0 OR FoundReligion=1 OR ReligiousHealCharges>0")
    s.append(("Religious units", table(["Unit", "Faith cost", "Moves", "Religious strength", "Spread charges", "Heal charges", "Evict %", "District"],
        [(c.n(r[0]), r[1], r[2], r[3], r[4], r[5], r[6], c.n(r[7])) for r in rel_units])))
    return write(out, "religion.md", "Religion: Beliefs, Religions, Religious Units",
                 "Pressure, conversion and theological combat constants are in global-parameters.md (RELIGION_*).", s)


# ============================================================ great people ==

def gen_great_people(c: Ctx, out):
    s = []
    s.append(("Great Person classes", table(["Class", "Unit", "District", "Max per player", "Available in timeline"],
        [(c.n(r["GreatPersonClassType"]), c.n(r["UnitType"]), c.n(r["DistrictType"]), r["MaxPlayerInstances"] or "",
          yesno(r["AvailableInTimeline"])) for r in c.q("SELECT * FROM GreatPersonClasses")])))
    s.append(("Base recruitment cost by era", table(["Era", "Great Person base cost"],
        [(c.n(r["EraType"]), r["GreatPersonBaseCost"]) for r in c.q("SELECT EraType, GreatPersonBaseCost FROM Eras ORDER BY ChronologyIndex")])))
    act = c.multi("SELECT GreatPersonIndividualType, ModifierId FROM GreatPersonIndividualActionModifiers")
    birth = c.multi("SELECT GreatPersonIndividualType, ModifierId FROM GreatPersonIndividualBirthModifiers")
    works = c.multi("SELECT GreatPersonIndividualType, GreatWorkObjectType FROM GreatWorks")
    rows = c.q("SELECT * FROM GreatPersonIndividuals ORDER BY GreatPersonClassType, EraType")
    by = defaultdict(list)
    for r in rows:
        by[r["GreatPersonClassType"]].append(r)
    for cls, lst in by.items():
        lst.sort(key=lambda r: era_idx(r["EraType"]))
        body = []
        for r in lst:
            g = r["GreatPersonIndividualType"]
            req = []
            for col in r.keys():
                if col.startswith("ActionRequires") and r[col] not in (None, 0, "0", ""):
                    v = r[col]
                    req.append(col.replace("ActionRequires", "") + ("" if v in (1, "1") else f"={c.n(v) if isinstance(v, str) else v}"))
            wk = works.get(g, [])
            body.append((c.n(g), c.n(r["EraType"]), r["ActionCharges"], ", ".join(req),
                         c.r.modifiers(act.get(g, [])),
                         c.r.modifiers(birth.get(g, [])),
                         (f"{len(wk)} x {c.n(wk[0]).replace('Greatworkobject ', '')}" if wk else "")))
        s.append((c.n(cls), table(["Individual", "Era", "Charges", "Activation requirements", "Activation effects", "Passive/on-recruit effects", "Great Works"], body)))
    gw = c.q("SELECT * FROM GreatWorkObjectTypes")
    s.append(("Great Work object types", table(["Type", "Value"], [(c.n(r["GreatWorkObjectType"]), r["Value"]) for r in gw])))
    gwy = c.q("SELECT o.GreatWorkObjectType t, y.YieldType, y.YieldChange, g.Tourism, count(*) n FROM GreatWorks g JOIN GreatWork_YieldChanges y USING(GreatWorkType) JOIN GreatWorkObjectTypes o USING(GreatWorkObjectType) GROUP BY 1,2,3,4")
    s.append(("Great Work yields (counts of works with each yield/tourism combination)", table(
        ["Object type", "Yield", "Amount", "Tourism", "Number of works"],
        [(c.n(r[0]), c.n(r[1]), r[2], r[3], r[4]) for r in gwy])))
    s.append(("Great Work slot compatibility", table(["Slot", "Accepts"],
        [(c.n(r[0]), c.n(r[1])) for r in c.q("SELECT * FROM GreatWork_ValidSubTypes")])))
    return write(out, "great-people.md", "Great People and Great Works",
                 "Activation requirement column names come from the GreatPersonIndividuals schema "
                 "(e.g. CompletedDistrictType=Campus means it must be used on a Campus).", s)


# ================================================================== civs ==

def gen_civs(c: Ctx, out):
    s = []
    tm = c.multi("SELECT TraitType, ModifierId FROM TraitModifiers")
    ctraits = c.multi("SELECT CivilizationType, TraitType FROM CivilizationTraits")
    ltraits = c.multi("SELECT LeaderType, TraitType FROM LeaderTraits")
    civ_leaders = c.multi("SELECT CivilizationType, LeaderType FROM CivilizationLeaders")
    uniques = defaultdict(list)
    for t, key in (("Units", "UnitType"), ("Buildings", "BuildingType"), ("Districts", "DistrictType"), ("Improvements", "ImprovementType")):
        for r in c.q(f"SELECT {key}, TraitType FROM {t} WHERE TraitType IS NOT NULL"):
            uniques[r[1]].append(c.n(r[0]))
    tnames = {r["TraitType"]: c.n.loc(r["Name"]) for r in c.q("SELECT TraitType, Name FROM Traits")}
    agendas = c.multi("SELECT LeaderType, AgendaType FROM HistoricalAgendas")
    bias = defaultdict(list)
    for t, col in (("StartBiasTerrains", "TerrainType"), ("StartBiasFeatures", "FeatureType"), ("StartBiasResources", "ResourceType")):
        for r in c.q(f"SELECT CivilizationType, {col}, Tier FROM {t}"):
            bias[r[0]].append(f"{c.n(r[1])} (tier {r[2]})")
    for r in c.q("SELECT CivilizationType, Tier FROM StartBiasRivers"):
        bias[r[0]].append(f"River (tier {r[1]})")

    def trait_text(t):
        unq = uniques.get(t, [])
        eff = c.r.modifiers(tm.get(t, []))
        name = tnames.get(t) or ""
        if name.startswith("LOC_") or not name:
            name = ""
        if not eff and not unq:
            return ""
        if not eff:
            return f"Unique: {', '.join(unq)}."
        return (f"**{name}**: " if name else "") + eff + (f" Uniques: {', '.join(unq)}." if unq else "") + "."

    civs = c.q("SELECT * FROM Civilizations WHERE StartingCivilizationLevelType='CIVILIZATION_LEVEL_FULL_CIV' ORDER BY CivilizationType")
    body = []
    for cv in civs:
        civ = cv["CivilizationType"]
        traits = [t for t in ctraits.get(civ, []) if t != "TRAIT_CIVILIZATION_MAJOR_CIV"] if False else ctraits.get(civ, [])
        body.append((c.n(civ), "; ".join(c.n(l) for l in civ_leaders.get(civ, [])), ", ".join(bias.get(civ, [])),
                     " ".join(filter(None, (trait_text(t) for t in traits)))))
    s.append(("Civilizations (civ abilities and civ uniques)", table(["Civilization", "Leaders", "Start bias", "Civ traits"], body)))
    body = []
    for civ, leaders in sorted(civ_leaders.items()):
        if civ not in {cv["CivilizationType"] for cv in civs}:
            continue
        for l in leaders:
            body.append((c.n(l), c.n(civ), ", ".join(c.n(a) for a in agendas.get(l, [])),
                         " ".join(filter(None, (trait_text(t) for t in ltraits.get(l, []) if not t.startswith("TRAIT_LEADER_MAJOR_CIV"))))))
    s.append(("Leaders (leader abilities and leader uniques)", table(["Leader", "Civilization", "Historical agenda", "Leader traits"], body)))
    am = c.multi("SELECT t.AgendaType, m.ModifierId FROM AgendaTraits t JOIN TraitModifiers m USING(TraitType)")
    rnd = {r["AgendaType"]: r for r in c.q("SELECT * FROM RandomAgendas")}
    s.append(("Agendas", table(["Agenda", "Random (hidden) pool", "Opinion modifiers (summary)"],
        [(c.n(r["AgendaType"]), yesno(r["AgendaType"] in rnd), "; ".join(sorted({c.r.modifier(m) for m in am.get(r["AgendaType"], [])}))[:400])
         for r in c.q("SELECT * FROM Agendas ORDER BY AgendaType")])))
    major = tm.get("TRAIT_LEADER_MAJOR_CIV", [])
    s.append(("Modifiers every major civ carries (TRAIT_LEADER_MAJOR_CIV)", table(["Modifier", "Effect"],
        [(m, c.r.modifier(m)) for m in major])))
    return write(out, "civilizations-leaders.md", "Civilizations and Leaders",
                 "Trait effects are rendered from modifiers; the bold trait name is the in-game ability name.", s)


def gen_city_states(c: Ctx, out):
    s = []
    tm = c.multi("SELECT TraitType, ModifierId FROM TraitModifiers")
    ltraits = c.multi("SELECT LeaderType, TraitType FROM LeaderTraits")
    tnames = {r["TraitType"]: c.n.loc(r["Name"]) for r in c.q("SELECT TraitType, Name FROM Traits")}
    cat = {r["Type"]: r["Value"] for r in c.q("SELECT * FROM TypeProperties WHERE Name='CityStateCategory'")}
    body = []
    for r in c.q("SELECT cl.CivilizationType, cl.LeaderType FROM CivilizationLeaders cl JOIN Civilizations cv USING(CivilizationType) WHERE cv.StartingCivilizationLevelType='CIVILIZATION_LEVEL_CITY_STATE' ORDER BY 1"):
        traits = ltraits.get(r["LeaderType"], [])
        body.append((c.n(r["CivilizationType"]), (cat.get(r["CivilizationType"]) or "").title(),
                     " ".join(f"**{tnames.get(t, c.n(t))}**: {c.r.modifiers(tm.get(t, []))}" for t in traits)))
    s.append(("City-states and suzerain bonuses", table(["City-state", "Type", "Suzerain bonus"], body)))
    body = []
    for r in c.q("SELECT LeaderType FROM Leaders WHERE InheritFrom='LEADER_MINOR_CIV_DEFAULT'"):
        for t in ltraits.get(r[0], []):
            for m in tm.get(t, []):
                body.append((c.n(r[0]).replace("Minor Civ ", ""), m, c.r.modifier(m)))
    s.append(("Envoy tier bonuses by city-state type", table(["Type", "Modifier", "Effect"], body)))
    return write(out, "city-states.md", "City-States",
                 "Envoy thresholds (1/3/6) and suzerain rules are in global-parameters.md (INFLUENCE_*) and the narrative spec.", s)


# ============================================================== governors ==

def gen_governors(c: Ctx, out):
    s = []
    gm = c.multi("SELECT GovernorPromotionType, ModifierId FROM GovernorPromotionModifiers")
    pre = c.multi("SELECT GovernorPromotionType, PrereqGovernorPromotion FROM GovernorPromotionPrereqs")
    sets = c.multi("SELECT GovernorType, GovernorPromotion FROM GovernorPromotionSets")
    xp2 = {r[0]: r for r in c.q("SELECT * FROM Governors_XP2")}
    rows = c.q("SELECT * FROM Governors")
    s.append(("Governors", table(["Governor", "Title", "Turns to establish", "Loyalty pressure", "Can serve city-states", "Unique to trait"],
        [(c.n(r["GovernorType"]), c.n.loc(r["ShortTitle"]) or c.n.loc(r["Title"]), r["TransitionStrength"], r["IdentityPressure"],
          yesno(r["AssignCityState"]), c.owner(r["TraitType"])) for r in rows])))
    for r in rows:
        g = r["GovernorType"]
        ps = c.q(f"SELECT * FROM GovernorPromotions WHERE GovernorPromotionType IN ({','.join('?' * len(sets.get(g, [])))}) ORDER BY Level, Column",
                 *sets.get(g, [])) if sets.get(g) else []
        s.append((c.n(g), table(["Promotion", "Tier", "Column", "Base ability", "Requires", "Effects"],
            [(c.n(p["GovernorPromotionType"]), p["Level"], p["Column"], yesno(p["BaseAbility"]),
              ", ".join(c.n(x) for x in pre.get(p["GovernorPromotionType"], [])),
              c.r.modifiers(gm.get(p["GovernorPromotionType"], []))) for p in ps])))
    src = []
    for t, k in (("CivicModifiers", "CivicType"), ("PolicyModifiers", "PolicyType"), ("TraitModifiers", "TraitType"), ("BuildingModifiers", "BuildingType")):
        for r in c.q(f"SELECT x.{k}, a.Value FROM {t} x JOIN Modifiers m ON m.ModifierId=x.ModifierId JOIN ModifierArguments a ON a.ModifierId=m.ModifierId "
                     f"WHERE m.ModifierType='MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS' AND a.Name='Delta'"):
            src.append((c.n(r[0]), k.replace("Type", ""), r[1]))
    s.append(("Sources of Governor Titles", table(["Source", "Kind", "Titles"], src)))
    return write(out, "governors.md", "Governors [R&F]", "", s)


# ======================================================== eras & moments ==

def gen_eras(c: Ctx, out):
    s = []
    rows = c.q("SELECT e.*, x1.GameEraMinimumTurns, x1.GameEraMaximumTurns, x1.LiberatedEnvoys, x2.GrievanceDecayRate, x2.TensionDecayRate, x2.TradeRouteMinimumEndTurnChange, x2.EraScoreThresholdShift FROM Eras e LEFT JOIN Eras_XP1 x1 USING(EraType) LEFT JOIN Eras_XP2 x2 USING(EraType) ORDER BY ChronologyIndex")
    s.append(("Eras", table(
        ["Era", "Index", "Warmonger points", "GP base cost", "Embarked strength", "Min / max turns [R&F]", "Liberated envoys",
         "Grievance decay [GS]", "Tension decay", "Trade route min end-turn change", "Era score threshold shift [GS]"],
        [(c.n(r["EraType"]), r["ChronologyIndex"], r["WarmongerPoints"], r["GreatPersonBaseCost"], r["EmbarkedUnitStrength"],
          f"{r['GameEraMinimumTurns']}/{r['GameEraMaximumTurns']}", r["LiberatedEnvoys"], r["GrievanceDecayRate"],
          r["TensionDecayRate"], r["TradeRouteMinimumEndTurnChange"], r["EraScoreThresholdShift"]) for r in rows])))
    s.append(("Amenities (happiness levels)", table(
        ["Level", "Min amenity balance", "Max", "Growth %", "Non-food yield %", "Rebellion points", "Loyalty/turn [R&F]"],
        [(c.n(r["HappinessType"]), r["MinimumAmenityScore"], r["MaximumAmenityScore"], r["GrowthModifier"], r["NonFoodYieldModifier"],
          r["RebellionPoints"], r["IdentityPerTurnChange"]) for r in c.q("SELECT h.*, x.IdentityPerTurnChange FROM Happinesses h LEFT JOIN Happinesses_XP1 x USING(HappinessType) ORDER BY MinimumAmenityScore")])))
    s.append(("Loyalty levels [R&F]", table(["Level", "Loyalty range", "Yield change", "Growth multiplier", "Identity change"],
        [(c.n.loc(r["Name"]), f"{r['LoyaltyMin']}-{r['LoyaltyMax']}", r["YieldChange"], r["GrowthChange"], r["IdentityChange"])
         for r in c.q("SELECT * FROM LoyaltyLevels ORDER BY LoyaltyMin")])))
    cm = c.multi("SELECT CommemorationType, ModifierId FROM CommemorationModifiers")
    s.append(("Dedications (commemorations) [R&F]", table(["Dedication", "Eras", "Effects (normal/dark: era score; golden: bonus)"],
        [(c.n.loc(r["CategoryDescription"]) or c.n(r["CommemorationType"]), f"{c.n(r['MinimumGameEra'])}-{c.n(r['MaximumGameEra'])}",
          c.r.modifiers(cm.get(r["CommemorationType"], []))) for r in c.q("SELECT * FROM CommemorationTypes")])))
    rows = c.q("SELECT * FROM Moments ORDER BY EraScore DESC, MomentType")
    s.append(("Historic moments [R&F]", table(["Moment", "Era score", "Interest", "Repeat cooldown", "Dedication", "Era window", "Obsolete era"],
        [(c.n(r["MomentType"]) if r["MomentType"] in c.n.names else c.n.loc(r["Name"]) or r["MomentType"], r["EraScore"], r["InterestLevel"],
          r["RepeatTurnCooldown"] or "", c.n(r["CommemorationType"]), f"{c.n(r['MinimumGameEra'])}-{c.n(r['MaximumGameEra'])}".strip("-"),
          c.n(r["ObsoleteEra"])) for r in rows])))
    return write(out, "eras-moments-loyalty.md", "Eras, Ages, Historic Moments, Amenities, Loyalty",
                 "Era score thresholds per age are GlobalParameters (see global-parameters.md, prefixes GOLDEN/DARK/ERA).", s)


# ========================================================== diplomacy etc ==

def gen_diplomacy(c: Ctx, out):
    s = []
    rows = c.q("SELECT a.*, x.FavorCost, x.GrievanceCost, x.PromiseType, x.GrievancesForRefusal FROM DiplomaticActions a LEFT JOIN DiplomaticActions_XP2 x USING(DiplomaticActionType)")
    s.append(("Diplomatic actions", table(
        ["Action", "Initiator civic/tech", "Gold cost", "Favor cost [GS]", "Duration", "Denounce turns required", "Warmonger %", "Notes"],
        [(c.n(r["DiplomaticActionType"]), c.n(r["InitiatorPrereqCivic"]) or c.n(r["InitiatorPrereqTech"]), r["Cost"], r["FavorCost"] or "",
          r["Duration"] or "", r["DenouncementTurnsRequired"] or "", r["WarmongerPercent"] or "",
          " ".join(k for k in ("RequiresAlliance", "RequiresConvertedCity", "RequiresOccupiedCity", "RequiresOccupiedFriendlyCity",
                                "RequiresWarOnAlliedCityState", "RequiresLeadXEras", "RequiresAdjacentEmpires") if r[k])) for r in rows])))
    s.append(("Wars / casus belli", table(["War type"], [(c.n(r["WarType"]),) for r in c.q("SELECT * FROM Wars")])))
    ae = c.q("SELECT * FROM AllianceEffects ORDER BY AllianceType, LevelRequirement")
    s.append(("Alliance effects [R&F]", table(["Alliance", "Level", "Effect"],
        [(c.n(r["AllianceType"]), r["LevelRequirement"], c.r.modifier(r["ModifierID"])) for r in ae])))
    s.append(("Diplomatic states", table(["State", "Relationship level", "Diplomatic yield bonus"],
        [(c.n(r["StateType"]), r["RelationshipLevel"], r["DiplomaticYieldBonus"]) for r in c.q("SELECT * FROM DiplomaticStates")])))
    s.append(("Diplomatic visibility sources", table(["Source", "Levels", "Flags"],
        [(c.n(r["VisibilitySourceType"]) , r["LevelRequired"] or "", " ".join(k for k in ("Trader", "Delegate", "Ally", "Spy", "FromCitizen") if r[k]))
         for r in c.q("SELECT * FROM DiplomaticVisibilitySources")])))
    ops = c.q("SELECT * FROM UnitOperations WHERE OperationType LIKE 'UNITOPERATION_SPY%' ORDER BY OperationType")
    s.append(("Spy operations", table(["Operation", "Turns", "Base probability", "Level prob change", "Enemy prob change", "Enemy level prob change", "Target district", "Unlock"],
        [(c.n(r["OperationType"]), r["Turns"], r["BaseProbability"], r["LevelProbChange"], r["EnemyProbChange"], r["EnemyLevelProbChange"],
          c.n(r["TargetDistrict"]), c.n(r["PrereqCivic"]) or c.n(r["PrereqTech"])) for r in ops])))
    s.append(("Deal items", table(["Item"], [(c.n(r["DealItemType"]),) for r in c.q("SELECT * FROM DealItems")])))
    s.append(("City-state quests", table(["Quest"], [(c.n(r["QuestType"]),) for r in c.q("SELECT * FROM Quests")])))
    return write(out, "diplomacy-espionage.md", "Diplomacy, Wars, Alliances, Espionage", "", s)


def gen_congress(c: Ctx, out):
    s = []
    eff = c.q("SELECT * FROM ResolutionEffects ORDER BY ResolutionType, WhichEffect")
    em = defaultdict(lambda: defaultdict(list))
    for r in eff:
        em[r["ResolutionType"]][r["WhichEffect"]].append(r["ModifierId"])
    rows = c.q("SELECT * FROM Resolutions")
    s.append(("World Congress resolutions [GS]", table(["Resolution", "Target kind", "Eras", "Option A", "Option B"],
        [(c.n(r["ResolutionType"]), (r["TargetKind"] or "").replace("_", " ").lower(), f"{c.n(r['EarliestEra'])}-{c.n(r['LatestEra'])}",
          c.r.modifiers(em[r["ResolutionType"]][1]), c.r.modifiers(em[r["ResolutionType"]][2])) for r in rows])))
    s.append(("Special sessions / discussions", table(["Discussion", "Proposal type", "Emergency"],
        [(c.n(r["DiscussionType"]) , c.n(r["ProposalType"]), c.n(r["EmergencyType"])) for r in c.q("SELECT * FROM Discussions")])))
    rows = c.q("SELECT e.*, x.Hostile, x.NoTarget, x.UIType FROM EmergencyAlliances e LEFT JOIN Emergencies_XP2 x USING(EmergencyType)")
    s.append(("Emergencies and competitions", table(["Emergency", "Trigger", "Duration", "Hostile", "UI type", "Goal trigger"],
        [(c.n(r["EmergencyType"]), (r["Trigger"] or "").replace("_", " ").lower(), r["Duration"], yesno(r["Hostile"]), r["UIType"],
          (r["GoalTrigger"] or "").replace("_", " ").lower()) for r in rows])))
    rew = c.q("SELECT * FROM EmergencyRewards ORDER BY EmergencyType")
    s.append(("Emergency rewards", table(["Emergency", "On success", "First place", "Top tier", "Bottom tier", "Effect"],
        [(c.n(r["EmergencyType"]), yesno(r["OnSuccess"]), yesno(r["FirstPlace"]), yesno(r["TopTier"]), yesno(r["BottomTier"]),
          c.r.modifier(r["ModifierID"])) for r in rew])))
    sc = c.q("SELECT * FROM EmergencyScoreSources ORDER BY EmergencyType")
    s.append(("Emergency / competition score sources", table(["Emergency", "Source", "Score"],
        [(c.n(r["EmergencyType"]), (r["ScoreSourceType"] or "").replace("_", " ").lower(), r["ScoreAmount"]) for r in sc])))
    return write(out, "world-congress-emergencies.md", "World Congress, Emergencies and Competitions",
                 "Congress timing, vote costs and Diplomatic Victory points are in global-parameters.md (WORLD_CONGRESS_*, DIPLOMATIC_*).", s)


def gen_climate(c: Ctx, out):
    s = []
    cols = ["RandomEventType", "Severity", "Hexes", "Duration", "Movement", "Spacing", "IceLoss", "ClimateChangePoints",
            "ChanceIncreasePerDegree", "FertilityRemovalChance", "MinTurnAtRisk", "NaturalWonder", "Global", "TargetCities"]
    s.append(("Random events (disasters)", table(cols,
        [[c.n(r[k]) if k == "RandomEventType" else r[k] for k in cols] for r in c.q("SELECT * FROM RandomEvents")])))
    s.append(("Event frequencies by disaster intensity", table(["Event", "Realism setting", "Occurrences per game"],
        [(c.n(r[0]), c.n(r[1]), r[2]) for r in c.q("SELECT * FROM RandomEvent_Frequencies")])))
    s.append(("Event damage", table(["Event", "Damage type", "%", "Min HP", "Max HP", "Coastal lowland %", "Fallout turns", "Extra range %"],
        [(c.n(r["RandomEventType"]), (r["DamageType"] or "").replace("_", " ").lower(), r["Percentage"], r["MinHP"], r["MaxHP"],
          r["CoastalLowlandPercentage"], r["FalloutDuration"], r["ExtraRangePercentage"]) for r in c.q("SELECT * FROM RandomEvent_Damages")])))
    s.append(("Event yield changes (fertility)", table(["Event", "Yield", "Feature", "% of tiles", "Amount", "Replace feature"],
        [(c.n(r["RandomEventType"]), c.n(r["YieldType"]), c.n(r["FeatureType"]), r["Percentage"], r["Amount"], c.n(r["ReplaceFeature"]))
         for r in c.q("SELECT * FROM RandomEvent_Yields")])))
    s.append(("Disaster intensity settings", table(["Setting", "% volcanoes active", "Extra range", "Climate change points"],
        [(c.n(r[0]), r[2], r[3], r[4]) for r in c.q("SELECT * FROM RealismSettings")])))
    s.append(("Coastal lowlands", table(["Lowland band", "Flood event", "Submerge event"],
        [(c.n(r[0]), c.n(r["FloodedEvent"]), c.n(r["SubmergedEvent"])) for r in c.q("SELECT * FROM CoastalLowlands")])))
    s.append(("Deforestation", table(["Level", "Max deforestation %", "Points per turn"],
        [(c.n(r[0]), r["MaxDeforestationPercent"], r["DeforestationPointsPerTurn"]) for r in c.q("SELECT * FROM DeforestationLevels")])
        + "\n" + table(["Effect", "Max average deforestation", "CO2 % modifier"],
        [(c.n(r[0]), r["MaxAverageDeforestation"], r["CO2PercentModifier"]) for r in c.q("SELECT * FROM DeforestationEffects")])))
    gp = c.q("SELECT Name, Value FROM GlobalParameters WHERE Name LIKE 'CLIMATE%' OR Name LIKE '%CO2%' OR Name LIKE 'SEA_LEVEL%' OR Name LIKE '%DISASTER%' OR Name LIKE 'RANDOM_EVENT%' OR Name LIKE '%POWER%' OR Name LIKE '%FLOOD%' OR Name LIKE '%DROUGHT%' OR Name LIKE '%STORM%' ORDER BY Name")
    s.append(("Climate-related global parameters", table(["Parameter", "Value"], [tuple(r) for r in gp])))
    return write(out, "climate-disasters.md", "Climate Change, Disasters, Power [GS]", "", s)


def gen_projects(c: Ctx, out):
    s = []
    gp = c.multi("SELECT ProjectType, '+' || Points || ' ' || GreatPersonClassType FROM Project_GreatPersonPoints")
    conv = c.multi("SELECT ProjectType, PercentOfProductionRate || '% of production -> ' || YieldType FROM Project_YieldConversions")
    pre = c.multi("SELECT ProjectType, PrereqProjectType FROM ProjectPrereqs")
    mods = c.multi("SELECT ProjectType, ModifierId FROM ProjectCompletionModifiers")
    rc = c.multi("SELECT ProjectType, StartProductionCost || ' ' || ResourceType FROM Project_ResourceCosts")
    xp2 = {r["ProjectType"]: r for r in c.q("SELECT * FROM Projects_XP2")}

    def ny(lst):
        return ", ".join(" ".join([x.split(" ")[0]] + [c.n(p) for p in x.split(" ")[1:]]) for x in lst)

    rows = c.q("SELECT * FROM Projects ORDER BY PrereqDistrict, Cost")
    s.append(("Projects", table(
        ["Project", "District", "Unlock", "Cost", "Cost progression", "Max per player", "Space race", "Requires", "Yield conversion",
         "GPP", "Amenities while active", "Resource cost", "Power while active [GS]", "Completion effects"],
        [(c.n(r["ProjectType"]), c.n(r["PrereqDistrict"]), c.n(r["PrereqTech"]) or c.n(r["PrereqCivic"]), r["Cost"],
          f"{r['CostProgressionModel']} {r['CostProgressionParam1']}".replace("COST_PROGRESSION_", "") if r["CostProgressionModel"] not in (None, "NO_COST_PROGRESSION") else "",
          r["MaxPlayerInstances"] if r["MaxPlayerInstances"] and r["MaxPlayerInstances"] > 0 else "", yesno(r["SpaceRace"]),
          ", ".join(c.n(p) for p in pre.get(r["ProjectType"], [])), ny(conv.get(r["ProjectType"], [])) if False else
          ", ".join(x.split(" -> ")[0] + " -> " + c.n(x.split(" -> ")[1]) for x in conv.get(r["ProjectType"], [])),
          ny(gp.get(r["ProjectType"], [])), r["AmenitiesWhileActive"] or "",
          ", ".join(x.split(" ")[0] + " " + c.n(x.split(" ")[1]) for x in rc.get(r["ProjectType"], [])),
          (xp2[r["ProjectType"]]["RequiredPowerWhileActive"] or "") if r["ProjectType"] in xp2 else "",
          c.r.modifiers(mods.get(r["ProjectType"], []))) for r in rows])))
    return write(out, "projects.md", "City Projects", "", s)


def gen_barbarians(c: Ctx, out):
    s = []
    s.append(("Barbarian tribes", table(["Tribe", "Coastal", "Required resource", "Resource range", "% ranged", "Turns to warrior spawn", "Raiding boldness", "City attack boldness"],
        [(r["TribeType"], yesno(r["IsCoastal"]), c.n(r["RequiredResource"]), r["ResourceRange"], r["PercentRangedUnits"], r["TurnsToWarriorSpawn"],
          r["RaidingBoldness"], r["CityAttackBoldness"]) for r in c.q("SELECT * FROM BarbarianTribes")])))
    s.append(("Barbarian attack forces", table(["Force", "Difficulty range", "Spawn rate", "Melee", "Ranged", "Siege", "Support", "Raiding"],
        [(r["AttackForceType"], f"{c.n(r['MinTargetDifficulty'])}-{c.n(r['MaxTargetDifficulty'])}", r["SpawnRate"],
          f"{r['NumMeleeUnits']} {r['MeleeTag']}", f"{r['NumRangeUnits']} {r['RangeTag']}", f"{r['NumSiegeUnits']} {r['SiegeTag']}",
          f"{r['NumSupportUnits']} {r['SupportTag']}", yesno(r["RaidingForce"])) for r in c.q("SELECT * FROM BarbarianAttackForces")])))
    gp = c.q("SELECT Name, Value FROM GlobalParameters WHERE Name LIKE 'BARBARIAN%' ORDER BY Name")
    s.append(("Barbarian global parameters", table(["Parameter", "Value"], [tuple(r) for r in gp])))
    sub = c.q("SELECT g.*, x.CityState, x.StrategicResources FROM GoodyHutSubTypes g LEFT JOIN GoodyHutSubTypes_XP2 x USING(SubTypeGoodyHut) ORDER BY GoodyHut")
    s.append(("Tribal village (goody hut) categories", table(["Category", "Weight", "Improvement"],
        [(c.n(r["GoodyHutType"]), r["Weight"], c.n(r["ImprovementType"])) for r in c.q("SELECT * FROM GoodyHuts")])))
    s.append(("Tribal village rewards", table(["Category", "Reward", "Weight", "Effect", "Min turn", "Needs unit", "Min one city"],
        [(c.n(r["GoodyHut"]), r["SubTypeGoodyHut"].replace("GOODYHUT_", "").replace("_", " ").lower(), r["Weight"],
          c.r.modifier(r["ModifierID"]) if r["ModifierID"] else
          ("relic" if r["Relic"] else f"heal {r['Heal']}" if r["Heal"] else f"{r['Experience']} XP" if r["Experience"] else
           f"upgrade unit" if r["UpgradeUnit"] else "trader" if r["Trader"] else ""),
          r["Turn"] or "", yesno(r["RequiresUnit"]), yesno(r["MinOneCity"])) for r in sub])))
    return write(out, "barbarians-goody-huts.md", "Barbarians and Tribal Villages", "", s)


GENERATORS = [
    gen_global_parameters, gen_game_setup, gen_terrain, gen_improvements, gen_districts, gen_buildings, gen_wonders,
    gen_units, gen_promotions, gen_tech, gen_civics, gen_governments, gen_religion, gen_great_people, gen_civs,
    gen_city_states, gen_governors, gen_eras, gen_diplomacy, gen_congress, gen_climate, gen_projects, gen_barbarians,
]


def main():
    db = sys.argv[1] if len(sys.argv) > 1 else "civ6_gs.sqlite"
    outdir = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "..", "specs", "civ6", "data")
    os.makedirs(outdir, exist_ok=True)
    c = Ctx(db)
    written = []
    for g in GENERATORS:
        try:
            written.append(g(c, outdir))
        except Exception as e:  # keep going; report at the end
            import traceback
            traceback.print_exc()
            print(f"FAILED {g.__name__}: {e}")
    index = ["# Civ VI Reference Data (generated)\n",
             "Tables extracted from the game's own rules database by `tools/civ6_extract`. "
             "Ruleset: Base + Rise and Fall + Gathering Storm + installed civ/leader packs; optional game modes and scenarios excluded. "
             "Effect text is generated from Modifiers and Requirements, not copied from the game's descriptions.\n"]
    for p in written:
        if p:
            with open(p, encoding="utf-8") as f:
                title = next((l[2:].strip() for l in f if l.startswith("# ")), os.path.basename(p))
            index.append(f"- [{title}]({os.path.basename(p)})")
    with open(os.path.join(outdir, "README.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER + "\n".join(index) + "\n")
    print(f"wrote {len([w for w in written if w])} files to {outdir}")


if __name__ == "__main__":
    main()
