#!/usr/bin/env python3
"""Keeps the Unreal SovereignCore module in step with the standalone builds.

Unreal compiles the rules core, the battle simulation and the dialogue layer through one wrapper .cpp per
source in unreal/Source/SovereignCore/Private/Core/ (each only #includes its file), so
core/, battle/ and diplomacy/ never hold an Unreal file. This check fails when the wrappers
and the sovereign_core, sovereign_battle or sovereign_diplomacy sources in their
CMakeLists.txt differ (the socket client, sovereign_diplomacy_http, stays out of Unreal).

  python3 tools/check_unreal_core_module.py          # check
  python3 tools/check_unreal_core_module.py --write  # regenerate the wrappers
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WRAPPERS = ROOT / "unreal" / "Source" / "SovereignCore" / "Private" / "Core"
# (library dir, CMake target, wrapper prefix, what it is)
LIBRARIES = [
    ("core", "sovereign_core", "SovCore_", "the core stays engine-independent"),
    ("battle", "sovereign_battle", "SovBattle_", "the battle simulation stays engine-independent"),
    ("diplomacy", "sovereign_diplomacy", "SovDiplomacy_", "the dialogue layer stays engine-independent"),
]


def library_sources(lib, target):
    cmake = ROOT / lib / "CMakeLists.txt"
    text = cmake.read_text(encoding="utf-8")
    block = re.search(r"add_library\(%s\s(.*?)\)" % target, text, re.S)
    if not block:
        raise SystemExit("%s/CMakeLists.txt: add_library(%s ...) not found" % (lib, target))
    return sorted(Path(s).name for s in re.findall(r"src/(\S+\.cpp)", block.group(1)))


def wrapper_text(lib, source, why):
    return (
        "// Generated by tools/check_unreal_core_module.py --write; do not edit.\n"
        "// Compiles %s/src/%s inside the SovereignCore module (%s).\n"
        '#include "%s/src/%s"\n' % (lib, source, why, lib, source)
    )


def main():
    write = "--write" in sys.argv[1:]
    expected = {}
    for lib, target, prefix, why in LIBRARIES:
        for s in library_sources(lib, target):
            expected[prefix + s] = wrapper_text(lib, s, why)
    prefixes = tuple(p for _, _, p, _ in LIBRARIES)
    present = {p.name: p for p in WRAPPERS.glob("*.cpp") if p.name.startswith(prefixes)} if WRAPPERS.exists() else {}
    problems = []
    if write:
        WRAPPERS.mkdir(parents=True, exist_ok=True)
        for name, path in present.items():
            if name not in expected:
                path.unlink()
        for name, text in expected.items():
            (WRAPPERS / name).write_text(text, encoding="utf-8", newline="\n")
        print("wrote %d wrappers to %s" % (len(expected), WRAPPERS.relative_to(ROOT)))
        return 0
    for name in sorted(set(expected) - set(present)):
        problems.append("missing wrapper %s" % name)
    for name in sorted(set(present) - set(expected)):
        problems.append("wrapper %s has no source" % name)
    for name in sorted(set(expected) & set(present)):
        if present[name].read_text(encoding="utf-8").replace("\r\n", "\n") != expected[name]:
            problems.append("wrapper %s is out of date" % name)
    for p in problems:
        print(p)
    if problems:
        print("run: python3 tools/check_unreal_core_module.py --write")
        return 1
    print("unreal core module check passed (%d sources)" % len(expected))
    return 0


if __name__ == "__main__":
    sys.exit(main())
