#!/usr/bin/env python3
"""Keeps the Unreal SovereignCore module in step with the standalone core build.

Unreal compiles the rules core through one wrapper .cpp per core source in
unreal/Source/SovereignCore/Private/Core/ (each only #includes its core file),
so core/ itself never holds an Unreal file. This check fails when the wrappers
and the sovereign_core sources in core/CMakeLists.txt differ.

  python3 tools/check_unreal_core_module.py          # check
  python3 tools/check_unreal_core_module.py --write  # regenerate the wrappers
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CMAKE = ROOT / "core" / "CMakeLists.txt"
WRAPPERS = ROOT / "unreal" / "Source" / "SovereignCore" / "Private" / "Core"
PREFIX = "SovCore_"


def core_sources():
    text = CMAKE.read_text(encoding="utf-8")
    block = re.search(r"add_library\(sovereign_core(.*?)\)", text, re.S)
    if not block:
        raise SystemExit("core/CMakeLists.txt: add_library(sovereign_core ...) not found")
    return sorted(Path(s).name for s in re.findall(r"src/(\S+\.cpp)", block.group(1)))


def wrapper_text(source):
    return (
        "// Generated by tools/check_unreal_core_module.py --write; do not edit.\n"
        "// Compiles core/src/%s inside the SovereignCore module (the core stays engine-independent).\n"
        '#include "core/src/%s"\n' % (source, source)
    )


def main():
    write = "--write" in sys.argv[1:]
    sources = core_sources()
    expected = {PREFIX + s: wrapper_text(s) for s in sources}
    present = {p.name: p for p in WRAPPERS.glob(PREFIX + "*.cpp")} if WRAPPERS.exists() else {}
    problems = []
    if write:
        WRAPPERS.mkdir(parents=True, exist_ok=True)
        for name, path in present.items():
            if name not in expected:
                path.unlink()
        for name, text in expected.items():
            (WRAPPERS / name).write_text(text, encoding="utf-8", newline="\n")
        print("wrote %d wrappers to %s" % (len(expected), WRAPPERS.relative_to(ROOT)))
        return 0
    for name in sorted(set(expected) - set(present)):
        problems.append("missing wrapper %s" % name)
    for name in sorted(set(present) - set(expected)):
        problems.append("wrapper %s has no core source" % name)
    for name in sorted(set(expected) & set(present)):
        if present[name].read_text(encoding="utf-8").replace("\r\n", "\n") != expected[name]:
            problems.append("wrapper %s is out of date" % name)
    for p in problems:
        print(p)
    if problems:
        print("run: python3 tools/check_unreal_core_module.py --write")
        return 1
    print("unreal core module check passed (%d sources)" % len(sources))
    return 0


if __name__ == "__main__":
    sys.exit(main())
