#!/usr/bin/env python3
"""Generate the rules core's baseline JSON data from the Civ VI reference tables.

Reads specs/civ6/data/*.md (themselves generated by tools/civ6_extract) and
writes data/rules/{globals,terrain,resources,units}.json. Sovereign's own
choices live in hand-written files beside them (civilizations.json,
setup.json) or in later rules layers, never in the generated files.

Usage (from the repo root):  python3 tools/rules_gen/gen_rules.py
Check mode for CI:            python3 tools/rules_gen/gen_rules.py --check
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "specs" / "civ6" / "data"
OUT = ROOT / "data" / "rules"

YIELD_WORDS = {
    "Food": "FOOD", "Production": "PRODUCTION", "Gold": "GOLD",
    "Science": "SCIENCE", "Culture": "CULTURE", "Faith": "FAITH",
}

# Terrain display names -> (id, climate base, relief). The tables list one
# "Mountain" row per climate in order, so mountains are named from the row
# above them.
TERRAIN_BASES = {
    "Grassland": ("TERRAIN_GRASS", "GRASSLAND"),
    "Plains": ("TERRAIN_PLAINS", "PLAINS"),
    "Desert": ("TERRAIN_DESERT", "DESERT"),
    "Tundra": ("TERRAIN_TUNDRA", "TUNDRA"),
    "Snow": ("TERRAIN_SNOW", "SNOW"),
    "Coast and Lake": ("TERRAIN_COAST", "COAST"),
    "Ocean": ("TERRAIN_OCEAN", "OCEAN"),
}

FEATURE_IDS = {
    "Desert Floodplains": "FEATURE_FLOODPLAINS",
    "Ice": "FEATURE_ICE",
    "Rainforest": "FEATURE_JUNGLE",
    "Woods": "FEATURE_FOREST",
    "Oasis": "FEATURE_OASIS",
    "Marsh": "FEATURE_MARSH",
    "Reef": "FEATURE_REEF",
    "Grassland Floodplains": "FEATURE_FLOODPLAINS_GRASSLAND",
    "Plains Floodplains": "FEATURE_FLOODPLAINS_PLAINS",
    "Geothermal Fissure": "FEATURE_GEOTHERMAL_FISSURE",
    "Volcano": "FEATURE_VOLCANO",
    "Volcanic Soil": "FEATURE_VOLCANIC_SOIL",
    "Burning Woods": "FEATURE_BURNING_FOREST",
    "Burnt Woods": "FEATURE_BURNT_FOREST",
    "Burning Rainforest": "FEATURE_BURNING_JUNGLE",
    "Burnt Rainforest": "FEATURE_BURNT_JUNGLE",
}
# Features the engine treats as impassable although the table has no column for it.
IMPASSABLE_FEATURES = {"FEATURE_ICE", "FEATURE_VOLCANO"}


def tables(path):
    """Yield (section heading, header cells, rows) for each table in a generated file."""
    section, header, rows = None, None, []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            if header:
                yield section, header, rows
            section, header, rows = line[3:].strip(), None, []
        elif line.startswith("|"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if header is None:
                header = cells
            elif set("".join(cells)) <= set("-: "):
                continue
            else:
                rows.append(dict(zip(header, cells)))
    if header:
        yield section, header, rows


def table(path, section):
    for sec, _, rows in tables(path):
        if sec == section:
            return rows
    raise SystemExit(f"{path.name}: section '{section}' not found")


def num(text, default=0):
    text = (text or "").strip()
    if not text:
        return default
    m = re.fullmatch(r"-?\d+(\.\d+)?", text)
    if not m:
        raise ValueError(f"not a number: {text!r}")
    return float(text) if "." in text else int(text)


def yields(text):
    out = {}
    for part in filter(None, (p.strip() for p in (text or "").split(","))):
        m = re.fullmatch(r"([+-]?\d+(?:\.\d+)?) (\w+)", part)
        if not m or m.group(2) not in YIELD_WORDS:
            raise ValueError(f"bad yield {part!r}")
        out[YIELD_WORDS[m.group(2)]] = num(m.group(1).lstrip("+"))
    return out


def snake(name):
    return re.sub(r"[^A-Z0-9]+", "_", name.upper()).strip("_")


def terrain_names():
    """Map every display name used in Valid-terrain columns to an id."""
    names = {}
    for disp, (tid, _) in TERRAIN_BASES.items():
        names[disp] = tid
        names[f"{disp} (Hills)"] = tid + "_HILLS"
    return names


def gen_terrain():
    terrains = []
    last_base = None
    for row in table(SPEC / "terrain-features-resources.md", "Terrains"):
        disp = row["Terrain"]
        hills_flag, mountain_flag = (row["Hills/Mountain"].split("/") + [""])[:2]
        if disp == "Mountain":
            tid, base = TERRAIN_BASES[last_base]
            tid += "_MOUNTAIN"
            relief = "MOUNTAIN"
            name = f"{last_base} Mountain"
        elif hills_flag.strip() == "yes":
            plain = disp.replace(" (Hills)", "")
            tid, base = TERRAIN_BASES[plain]
            tid += "_HILLS"
            relief = "HILLS"
            name = disp
        else:
            tid, base = TERRAIN_BASES[disp]
            relief = "FLAT"
            name = disp
            last_base = disp
        sight_mod, sight_through = (row["Sight mod / through"].split("/") + ["0"])[:2]
        water, shallow = (row["Water/shallow"].split("/") + [""])[:2]
        t = {
            "id": tid, "name": name, "base": base, "relief": relief,
            "yields": yields(row["Yields"]),
            "moveCost": num(row["Move cost"], 1),
            "defense": num(row["Defense"]),
            "appeal": num(row["Appeal"]),
            "sightModifier": num(sight_mod),
            "sightThrough": num(sight_through),
        }
        if row["Impassable"] == "yes":
            t["impassable"] = True
        if water.strip() == "yes":
            t["water"] = True
        if shallow.strip() == "yes":
            t["shallowWater"] = True
        terrains.append(t)

    tnames = terrain_names()
    features = []
    for row in table(SPEC / "terrain-features-resources.md", "Features"):
        fid = FEATURE_IDS[row["Feature"]]
        valid = []
        for v in (x.strip() for x in row["Valid terrains"].split(",")):
            if v == "Mountain":
                continue  # volcanoes: every mountain, added below
            if v and tnames[v] not in valid:
                valid.append(tnames[v])
        if row["Feature"] == "Volcano":
            valid = [t["id"] for t in terrains if t["relief"] == "MOUNTAIN"]
        f = {
            "id": fid, "name": row["Feature"],
            "yields": yields(row["Yields"]),
            "moveChange": num(row["Move change"]),
            "defense": num(row["Defense"]),
            "appeal": num(row["Appeal"]),
            "sightThrough": num(row["Sight-blocking"]),
            "validTerrains": valid,
        }
        if row["Removable / remove tech"].startswith("yes"):
            f["removable"] = True
        if row["Fresh water"] == "yes":
            f["freshWater"] = True
        if fid in IMPASSABLE_FEATURES:
            f["impassable"] = True
        features.append(f)
    return {"terrains": terrains, "features": features}


def gen_resources():
    tnames = terrain_names()
    fnames = FEATURE_IDS
    out = []
    for section, cls in (("Bonus resources", "BONUS"), ("Luxury resources", "LUXURY"),
                         ("Strategic resources", "STRATEGIC")):
        for row in table(SPEC / "terrain-features-resources.md", section):
            land, sea = (row["Frequency/sea"].split("/") + ["0"])[:2]
            terr, feat = [], []
            for v in (x.strip() for x in row["Valid terrain/feature"].split(",")):
                if not v:
                    continue
                if v in tnames:
                    terr.append(tnames[v])
                elif v in fnames:
                    feat.append(fnames[v])
                else:
                    raise ValueError(f"resource {row['Resource']}: unknown place {v!r}")
            r = {
                "id": "RESOURCE_" + snake(row["Resource"]), "name": row["Resource"], "class": cls,
                "yields": yields(row["Yields"]),
                "frequency": num(land), "seaFrequency": num(sea),
                "validTerrains": terr, "validFeatures": feat,
            }
            if row["Revealed by"]:
                r["revealTech"] = "TECH_" + snake(row["Revealed by"])
            out.append(r)
    return {"resources": out}


def gen_units():
    out = []
    for row in table(SPEC / "units.md", "Units"):
        if row.get("Unique to"):
            continue  # Sovereign defines its own uniques (leaders-and-art-style.md)
        cls = row["Class"]
        special = row["Special"]
        layer = "CIVILIAN" if cls == "civilian" else "SUPPORT" if cls == "Support" else "MILITARY"
        combat = num(row["CS"])
        u = {
            "id": "UNIT_" + snake(row["Unit"]), "name": row["Unit"],
            "class": snake(cls), "domain": row["Domain"].upper(), "layer": layer,
            "cost": num(row["Cost"]), "maintenance": num(row["Gold maint."]),
            "combat": combat, "ranged": num(row["RS"]), "range": num(row["Range"]),
            "moves": num(row["Moves"], 0), "sight": num(row["Sight"], 2),
        }
        if combat > 0 and "no ZOC" not in special and row["Domain"] != "Air":
            u["zoneOfControl"] = True
        if "found city" in special:
            u["foundCity"] = True
        m = re.search(r"charges (\d+)", special)
        if m:
            u["buildCharges"] = int(m.group(1))
        if row["Unlock"]:
            u["unlock"] = row["Unlock"]
        out.append(u)
    return {"units": out}


def gen_globals():
    values = {}
    for _, header, rows in tables(SPEC / "global-parameters.md"):
        if header[:2] != ["Parameter", "Value"]:
            continue
        for row in rows:
            try:
                values[row["Parameter"]] = num(row["Value"])
            except ValueError:
                pass  # text-valued parameters are not rules numbers
    return {"globals": dict(sorted(values.items()))}


HEADER = {"_generated": "by tools/rules_gen/gen_rules.py from specs/civ6/data; do not edit by hand"}


def render(doc):
    return json.dumps({**HEADER, **doc}, indent=1, ensure_ascii=False) + "\n"


def main():
    check = "--check" in sys.argv
    outputs = {
        "globals.json": gen_globals(),
        "terrain.json": gen_terrain(),
        "resources.json": gen_resources(),
        "units.json": gen_units(),
    }
    stale = []
    for name, doc in outputs.items():
        path = OUT / name
        text = render(doc)
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    if stale:
        print("stale generated rules:", ", ".join(stale), "- rerun tools/rules_gen/gen_rules.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
