#!/usr/bin/env python3
"""Generate the rules core's baseline JSON data from the Civ VI reference tables.

Reads specs/civ6/data/*.md (themselves generated by tools/civ6_extract) and
writes data/rules/{globals,terrain,resources,promotions,units,districts,barbarians,buildings,techs,civics,
governments,policies,improvements}.json. Sovereign's own choices live in hand-written files
beside them (civilizations.json, setup.json, modifiers.json) or in later rules
layers, never in the generated files.

Usage (from the repo root):  python3 tools/rules_gen/gen_rules.py
Check mode for CI:            python3 tools/rules_gen/gen_rules.py --check
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "specs" / "civ6" / "data"
OUT = ROOT / "data" / "rules"

YIELD_WORDS = {
    "Food": "FOOD", "Production": "PRODUCTION", "Gold": "GOLD",
    "Science": "SCIENCE", "Culture": "CULTURE", "Faith": "FAITH",
}

# Terrain display names -> (id, climate base, relief). The tables list one
# "Mountain" row per climate in order, so mountains are named from the row
# above them.
TERRAIN_BASES = {
    "Grassland": ("TERRAIN_GRASS", "GRASSLAND"),
    "Plains": ("TERRAIN_PLAINS", "PLAINS"),
    "Desert": ("TERRAIN_DESERT", "DESERT"),
    "Tundra": ("TERRAIN_TUNDRA", "TUNDRA"),
    "Snow": ("TERRAIN_SNOW", "SNOW"),
    "Coast and Lake": ("TERRAIN_COAST", "COAST"),
    "Ocean": ("TERRAIN_OCEAN", "OCEAN"),
}

FEATURE_IDS = {
    "Desert Floodplains": "FEATURE_FLOODPLAINS",
    "Ice": "FEATURE_ICE",
    "Rainforest": "FEATURE_JUNGLE",
    "Woods": "FEATURE_FOREST",
    "Oasis": "FEATURE_OASIS",
    "Marsh": "FEATURE_MARSH",
    "Reef": "FEATURE_REEF",
    "Grassland Floodplains": "FEATURE_FLOODPLAINS_GRASSLAND",
    "Plains Floodplains": "FEATURE_FLOODPLAINS_PLAINS",
    "Geothermal Fissure": "FEATURE_GEOTHERMAL_FISSURE",
    "Volcano": "FEATURE_VOLCANO",
    "Volcanic Soil": "FEATURE_VOLCANIC_SOIL",
    "Burning Woods": "FEATURE_BURNING_FOREST",
    "Burnt Woods": "FEATURE_BURNT_FOREST",
    "Burning Rainforest": "FEATURE_BURNING_JUNGLE",
    "Burnt Rainforest": "FEATURE_BURNT_JUNGLE",
}
# Features the engine treats as impassable although the table has no column for it.
IMPASSABLE_FEATURES = {"FEATURE_ICE", "FEATURE_VOLCANO"}


def tables(path):
    """Yield (section heading, header cells, rows) for each table in a generated file."""
    section, header, rows = None, None, []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            if header:
                yield section, header, rows
            section, header, rows = line[3:].strip(), None, []
        elif line.startswith("|"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if header is None:
                header = cells
            elif set("".join(cells)) <= set("-: "):
                continue
            else:
                rows.append(dict(zip(header, cells)))
    if header:
        yield section, header, rows


def table(path, section):
    for sec, _, rows in tables(path):
        if sec == section:
            return rows
    raise SystemExit(f"{path.name}: section '{section}' not found")


def num(text, default=0):
    text = (text or "").strip()
    if not text:
        return default
    m = re.fullmatch(r"-?\d+(\.\d+)?", text)
    if not m:
        raise ValueError(f"not a number: {text!r}")
    return float(text) if "." in text else int(text)


def yields(text):
    out = {}
    for part in filter(None, (p.strip() for p in (text or "").split(","))):
        m = re.fullmatch(r"([+-]?\d+(?:\.\d+)?) (\w+)", part)
        if not m or m.group(2) not in YIELD_WORDS:
            raise ValueError(f"bad yield {part!r}")
        out[YIELD_WORDS[m.group(2)]] = num(m.group(1).lstrip("+"))
    return out


def snake(name):
    return re.sub(r"[^A-Z0-9]+", "_", name.upper()).strip("_")


def terrain_names():
    """Map every display name used in Valid-terrain columns to an id."""
    names = {}
    for disp, (tid, _) in TERRAIN_BASES.items():
        names[disp] = tid
        names[f"{disp} (Hills)"] = tid + "_HILLS"
    return names


def gen_terrain():
    terrains = []
    last_base = None
    for row in table(SPEC / "terrain-features-resources.md", "Terrains"):
        disp = row["Terrain"]
        hills_flag, mountain_flag = (row["Hills/Mountain"].split("/") + [""])[:2]
        if disp == "Mountain":
            tid, base = TERRAIN_BASES[last_base]
            tid += "_MOUNTAIN"
            relief = "MOUNTAIN"
            name = f"{last_base} Mountain"
        elif hills_flag.strip() == "yes":
            plain = disp.replace(" (Hills)", "")
            tid, base = TERRAIN_BASES[plain]
            tid += "_HILLS"
            relief = "HILLS"
            name = disp
        else:
            tid, base = TERRAIN_BASES[disp]
            relief = "FLAT"
            name = disp
            last_base = disp
        sight_mod, sight_through = (row["Sight mod / through"].split("/") + ["0"])[:2]
        water, shallow = (row["Water/shallow"].split("/") + [""])[:2]
        t = {
            "id": tid, "name": name, "base": base, "relief": relief,
            "yields": yields(row["Yields"]),
            "moveCost": num(row["Move cost"], 1),
            "defense": num(row["Defense"]),
            "appeal": num(row["Appeal"]),
            "sightModifier": num(sight_mod),
            "sightThrough": num(sight_through),
        }
        if row["Impassable"] == "yes":
            t["impassable"] = True
        if water.strip() == "yes":
            t["water"] = True
        if shallow.strip() == "yes":
            t["shallowWater"] = True
        terrains.append(t)

    tnames = terrain_names()
    features = []
    for row in table(SPEC / "terrain-features-resources.md", "Features"):
        fid = FEATURE_IDS[row["Feature"]]
        valid = []
        for v in (x.strip() for x in row["Valid terrains"].split(",")):
            if v == "Mountain":
                continue  # volcanoes: every mountain, added below
            if v and tnames[v] not in valid:
                valid.append(tnames[v])
        if row["Feature"] == "Volcano":
            valid = [t["id"] for t in terrains if t["relief"] == "MOUNTAIN"]
        f = {
            "id": fid, "name": row["Feature"],
            "yields": yields(row["Yields"]),
            "moveChange": num(row["Move change"]),
            "defense": num(row["Defense"]),
            "appeal": num(row["Appeal"]),
            "sightThrough": num(row["Sight-blocking"]),
            "validTerrains": valid,
        }
        if row["Removable / remove tech"].startswith("yes"):
            f["removable"] = True
            tech = row["Removable / remove tech"][3:].strip()
            if tech:
                f["removeTech"] = unlock_id(tech)
        harvest = harvest_yields(row["Harvest yields"])
        if harvest:
            f["harvestYields"] = harvest
        if row["Fresh water"] == "yes":
            f["freshWater"] = True
        if fid in IMPASSABLE_FEATURES:
            f["impassable"] = True
        features.append(f)
    return {"terrains": terrains, "features": features}


def harvest_yields(text):
    """'Production 10, Food 10' or '20 Food' -> {"PRODUCTION": 10, "FOOD": 10}."""
    out = {}
    for part in filter(None, (p.strip() for p in (text or "").split(","))):
        m = re.fullmatch(r"(\w+) (\d+)", part) or re.fullmatch(r"(\d+) (\w+)", part)
        a, b = m.group(1), m.group(2)
        word, amount = (a, b) if a in YIELD_WORDS else (b, a)
        out[YIELD_WORDS[word]] = int(amount)
    return out


def gen_resources():
    tnames = terrain_names()
    accumulation = {r["Resource"]: r for r in table(SPEC / "terrain-features-resources.md",
                                                    "Strategic resource accumulation and power [GS]")}
    fnames = FEATURE_IDS
    out = []
    for section, cls in (("Bonus resources", "BONUS"), ("Luxury resources", "LUXURY"),
                         ("Strategic resources", "STRATEGIC")):
        for row in table(SPEC / "terrain-features-resources.md", section):
            land, sea = (row["Frequency/sea"].split("/") + ["0"])[:2]
            terr, feat = [], []
            for v in (x.strip() for x in row["Valid terrain/feature"].split(",")):
                if not v:
                    continue
                if v in tnames:
                    terr.append(tnames[v])
                elif v in fnames:
                    feat.append(fnames[v])
                else:
                    raise ValueError(f"resource {row['Resource']}: unknown place {v!r}")
            r = {
                "id": "RESOURCE_" + snake(row["Resource"]), "name": row["Resource"], "class": cls,
                "yields": yields(row["Yields"]),
                "frequency": num(land), "seaFrequency": num(sea),
                "validTerrains": terr, "validFeatures": feat,
            }
            if row["Revealed by"]:
                r["revealTech"] = "TECH_" + snake(row["Revealed by"])
            if cls == "LUXURY" and row["Amenities"]:
                r["amenityCities"] = num(row["Amenities"])  # +1 amenity to this many cities
            m = re.fullmatch(r"(.+) \((.+)\)", row["Harvest"])
            if m:
                r["harvestYields"] = harvest_yields(m.group(1))
                r["harvestTech"] = unlock_id(m.group(2))
            if row["Resource"] in accumulation:
                acc = accumulation[row["Resource"]]
                r["accumulation"] = num(acc["Base / improved extraction per turn"].split("/")[1])
                r["stockpileCap"] = num(acc["Stockpile cap"])
            out.append(r)
    return {"resources": out}


def gen_units():
    out = []
    for row in table(SPEC / "units.md", "Units"):
        if row.get("Unique to"):
            continue  # Sovereign defines its own uniques (leaders-and-art-style.md)
        cls = row["Class"]
        special = row["Special"]
        layer = "CIVILIAN" if cls == "civilian" else "SUPPORT" if cls == "Support" else "MILITARY"
        combat = num(row["CS"])
        u = {
            "id": "UNIT_" + snake(row["Unit"]), "name": row["Unit"],
            "class": snake(cls), "domain": row["Domain"].upper(), "layer": layer,
            "cost": num(row["Cost"]), "maintenance": num(row["Gold maint."]),
            "combat": combat, "ranged": num(row["RS"]), "range": num(row["Range"]),
            "moves": num(row["Moves"], 0), "sight": num(row["Sight"], 2),
        }
        if combat > 0 and "no ZOC" not in special and row["Domain"] != "Air":
            u["zoneOfControl"] = True
        if "found city" in special:
            u["foundCity"] = True
        m = re.search(r"charges (\d+)", special)
        if m and "heal charges" not in special:
            u["buildCharges"] = int(m.group(1))
        prog = row["Cost progression"].split()
        if len(prog) == 2 and prog[0] == "PREVIOUS_COPIES":
            u["costProgression"] = int(prog[1])
        m = re.search(r"pop cost (\d+)", special)
        if m:
            u["popCost"] = int(m.group(1))
        m = re.search(r"needs pop (\d+)", special)
        if m:
            u["minPopulation"] = int(m.group(1))
        if "must purchase" in special:
            u["mustPurchase"] = True
        # Great People (cost 1, never bought) come from great person points and spies from
        # espionage; neither is trained in a city queue. Both systems are not modelled yet.
        if (num(row["Cost"]) <= 1 and not row["Purchase"]) or special == "spy":
            u["trainable"] = False
        # "needs Temple" / "needs Prasat/Stave Church/Temple": any one of the buildings in the
        # city (unique buildings Sovereign does not have are dropped).
        m = re.search(r"needs (?!pop )(.+?)(?= must purchase|$)", special)
        if m:
            known = {r["Building"] for r in table(SPEC / "buildings.md", "Buildings") if not r.get("Unique to")}
            need = ["BUILDING_" + snake(b) for b in m.group(1).split("/") if b in known]
            if need:
                u["needsBuilding"] = need
        if row["Purchase"]:
            u["purchaseYield"] = row["Purchase"].upper()
        if row["Unlock"]:
            u["unlock"] = unlock_id(row["Unlock"])
        m = re.fullmatch(r"(\w+) (\d+)", row["Strategic cost [GS]"])
        if m:
            u["strategicCost"] = {"resource": "RESOURCE_" + snake(m.group(1)), "amount": int(m.group(2))}
        if row["Upgrades to"]:
            u["upgradesTo"] = "UNIT_" + snake(row["Upgrades to"])
        if row["Forced obsolete"]:
            u["obsoleteWith"] = unlock_id(row["Forced obsolete"])
        if num(row["Bombard"]):
            u["bombard"] = num(row["Bombard"])
        m = re.fullmatch(r"(\d+) (\w+)/turn", row["Resource maint. [GS]"])
        if m:
            u["resourceMaintenance"] = {"resource": "RESOURCE_" + snake(m.group(2)), "amount": int(m.group(1))}
        if snake(cls) in promotion_classes():
            u["promotionClass"] = "PROMOTION_CLASS_" + snake(cls)
        abilities = [a.strip() for a in row["Innate abilities (via class tags)"].split(",") if a.strip()]
        if abilities:
            u["abilities"] = ["ABILITY_" + snake(a) for a in abilities]
        out.append(u)
    known = {u["id"] for u in out}
    for u in out:
        if u.get("upgradesTo") not in known:
            u.pop("upgradesTo", None)  # upgrades into a unique unit
    for row in table(SPEC / "units.md", "Unit capture results"):
        for u in out:
            if u["name"] == row["Captured"]:
                u["capturedAs"] = "UNIT_" + snake(row["Becomes"])
    return {"units": out}


# ---------------------------------------------------------------- promotions

def promotion_classes():
    return {snake(sec) for sec, header, _ in tables(SPEC / "promotions.md") if header and header[0] == "Promotion"}


# Abilities whose table row has no effect text, or whose text reads the wrong
# way round; the engine applies them through combat globals.
ABILITY_OVERRIDES = {
    "Ranged Attack District Debuff": [{"kind": "RANGED_VS_DISTRICT"}],
    "Air Fighter Attack District Debuff": [{"kind": "RANGED_VS_DISTRICT"}],
    "Bombard Attack Unit Debuff": [{"kind": "BOMBARD_VS_UNIT"}],
    "Air Bomber Attack Unit Debuff": [{"kind": "BOMBARD_VS_UNIT"}],
    "No Move and Shoot": [{"kind": "NO_ATTACK_AFTER_MOVE"}],
}
# Ability class tags that name several unit classes.
TAG_ALIASES = {"AIRCRAFT": ["AIR_FIGHTER", "AIR_BOMBER"], "GIANT_DEATH_ROBOT": ["GDR"]}


def condition_atom(text):
    """One condition of a combat bonus ('vs Melee', 'NOT when attacking') as JSON."""
    a = {}
    if text.startswith("NOT "):
        a["not"] = True
        text = text[4:]
    m = re.fullmatch(r"vs (.+?)(?: units)?", text)
    tile = re.fullmatch(r"tile is (.+)", text)
    ctype = re.fullmatch(r"combat type matches \(CombatType=Combat (Melee|Ranged)\)", text)
    if text == "when attacking":
        a["atom"] = "ATTACKING"
    elif text == "vs a district/city":
        a["atom"] = "VS_DISTRICT"
    elif m and m.group(1) in ("Land", "Sea", "Air"):
        a.update(atom="VS_DOMAIN", value={"Land": "LAND", "Sea": "SEA", "Air": "AIR"}[m.group(1)])
    elif m:
        a.update(atom="VS_CLASS", value=snake(m.group(1)))
    elif ctype:
        a.update(atom="COMBAT_TYPE", value=ctype.group(1).upper())
    elif tile and tile.group(1) == "Hills":
        a["atom"] = "TILE_HILLS"
    elif tile and tile.group(1) in FEATURE_IDS:
        a.update(atom="TILE_FEATURE", value=FEATURE_IDS[tile.group(1)])
    elif tile and tile.group(1) in terrain_names():
        a.update(atom="TILE_TERRAIN", value=terrain_names()[tile.group(1)])
    elif text == "opponent is fortified":
        a["atom"] = "OPPONENT_FORTIFIED"
    elif text == "opponent is wounded":
        a["atom"] = "OPPONENT_WOUNDED"
    elif text == "plot district is defended":
        a["atom"] = "VS_DISTRICT"
    elif text == "plot has any district":
        a["atom"] = "DISTRICT_TILE"
    elif text == "in own territory":
        a["atom"] = "OWN_TERRITORY"
    else:
        a.update(atom="UNTRACKED", value=text)
    return a


def unit_effects(text):
    """Effect text of a promotion or ability -> list of effect objects. Conditions
    are 'A and B or C' = A and (B or C): a list of any-of groups that must all hold."""
    out = []
    for part in filter(None, (p.strip() for p in text.split("; "))):
        m = re.fullmatch(r"([+-]\d+) Combat Strength in combat(?: where (.*))?", part)
        simple = [
            (r"\+(\d+) Movement", "MOVES"), (r"\+(\d+) range", "RANGE"), (r"\+(\d+) sight", "SIGHT"),
            (r"\+(\d+) attack\(s\) per turn", "ATTACKS"), (r"\+(\d+)% combat XP", "XP_PERCENT"),
            (r"(\d+)% flanking bonus", "FLANKING_PERCENT"), (r"(\d+)% support bonus", "SUPPORT_PERCENT"),
        ]
        flags = {
            "can move after attacking": "MOVE_AFTER_ATTACK", "can attack after moving": "ATTACK_AFTER_MOVE",
            "adjust unit ignore zoc (Ignore=yes)": "IGNORE_ZOC", "adjust unit exert zoc (Exert=yes)": "EXERT_ZOC",
            "no river crossing penalty": "NO_RIVER_PENALTY", "no combat penalty from damage": "NO_WOUNDED_PENALTY",
            "can heal after moving/attacking": "HEAL_AFTER_ACTION", "can enter foreign territory": "IGNORE_BORDERS",
            "Melee units deal full damage to walls": "WALL_FULL_DAMAGE", "Melee units bypass walls": "BYPASS_WALLS",
        }
        if m:
            e = {"kind": "STRENGTH", "amount": int(m.group(1))}
            if m.group(2):
                e["when"] = [[condition_atom(o.strip()) for o in g.split(" or ")] for g in m.group(2).split(" and ")]
            out.append(e)
            continue
        for pattern, kind in simple:
            sm = re.fullmatch(pattern, part)
            if sm:
                out.append({"kind": kind, "amount": int(sm.group(1))})
                break
        else:
            out.append({"kind": flags[part]} if part in flags else {"kind": "UNTRACKED", "text": part})
    return out


def gen_promotions():
    promos = []
    for sec, header, rows in tables(SPEC / "promotions.md"):
        if not header or header[0] != "Promotion":
            continue
        for row in rows:
            p = {"id": "PROMOTION_" + snake(row["Promotion"]), "name": row["Promotion"],
                 "class": "PROMOTION_CLASS_" + snake(sec), "tier": num(row["Tier"])}
            req = [x.strip() for x in row["Requires (any)"].split(",") if x.strip()]
            if req:
                p["requires"] = ["PROMOTION_" + snake(x) for x in req]
            p["effects"] = unit_effects(row["Effect"])
            promos.append(p)
    abilities = []
    for row in table(SPEC / "units.md", "Unit abilities"):
        tags = []
        for t in (x.strip().upper() for x in row["Applies to class tags"].split(",") if x.strip()):
            tags += TAG_ALIASES.get(t, [t])
        a = {"id": "ABILITY_" + snake(row["Ability"]), "name": row["Ability"], "classes": tags}
        if row["Inactive by default"]:
            a["inactive"] = True
        a["effects"] = ABILITY_OVERRIDES.get(row["Ability"]) or unit_effects(row["Effects"])
        abilities.append(a)
    return {"promotions": promos, "abilities": abilities}


def gen_buildings():
    rows = [r for r in table(SPEC / "buildings.md", "Buildings") if not r.get("Unique to")]
    ids = {r["Building"]: "BUILDING_" + snake(r["Building"]) for r in rows}
    out = []
    for row in rows:
        b = {
            "id": ids[row["Building"]], "name": row["Building"],
            "district": "DISTRICT_" + snake(row["District"]),
            "cost": num(row["Cost"]), "maintenance": num(row["Maint."]),
            "yields": yields(row["Yields"]),
        }
        if row["Unlock"]:
            b["unlock"] = unlock_id(row["Unlock"])
        if row["Housing"]:
            b["housing"] = num(row["Housing"])
        if row["Amenity"]:
            b["amenities"] = num(row["Amenity"])
        m = re.fullmatch(r"(\d+) HP / \+(\d+)", row["Defense"])
        if m:
            b["outerDefenseHp"], b["defense"] = int(m.group(1)), int(m.group(2))
        reqs = [ids[x.strip()] for x in row["Requires"].split(",") if x.strip() in ids]
        if reqs:
            b["requires"] = reqs
        if row["Placement"] == "river":
            b["needsRiver"] = True
        if row["Purchase"] == "Gold":
            b["purchasable"] = True
        if "melee attacks cannot damage the walls" in row["Modifiers"]:
            b["meleeCannotDamageWalls"] = True
        if "walls cannot be bypassed" in row["Modifiers"]:
            b["wallsCannotBeBypassed"] = True
        out.append(b)
    return {"buildings": out}


# Civ VI BarbarianTribes.MeleeTag per tribe (the reference table leaves the tag out).
TRIBE_MELEE_CLASS = {"TRIBE_NAVAL": "NAVAL_MELEE", "TRIBE_CAVALRY": "LIGHT_CAVALRY", "TRIBE_MELEE": "MELEE"}


def gen_barbarians():
    out = []
    for row in table(SPEC / "barbarians-goody-huts.md", "Barbarian tribes"):
        t = {"id": row["Tribe"], "rangedPercent": num(row["% ranged"]),
             "spawnTurns": num(row["Turns to warrior spawn"]), "raidBoldness": num(row["Raiding boldness"]),
             "attackBoldness": num(row["City attack boldness"]), "unitClass": TRIBE_MELEE_CLASS[row["Tribe"]]}
        if row["Coastal"] == "yes":
            t["coastal"] = True
        if row["Required resource"]:
            t["resource"] = "RESOURCE_" + snake(row["Required resource"])
            t["resourceRange"] = num(row["Resource range"])
        out.append(t)
    return {"barbarianTribes": out}


# Districts the core places so far (MVP-5, the Harbor with naval play); the rest need
# placement rules not modelled yet (flat land, rivers, aqueduct rules) and arrive with their systems.
PLACEABLE_DISTRICTS = ["Campus", "Holy Site", "Commercial Hub", "Encampment", "Theater Square", "Industrial Zone", "Harbor"]
FEATURE_NAMES = {"Rainforest": "FEATURE_JUNGLE", "Woods": "FEATURE_FOREST", "Reef": "FEATURE_REEF",
                 "Geothermal Fissure": "FEATURE_GEOTHERMAL_FISSURE"}
IMPROVEMENT_NAMES = {"Quarry": "IMPROVEMENT_QUARRY", "Mine": "IMPROVEMENT_MINE", "Lumber Mill": "IMPROVEMENT_LUMBER_MILL"}


def district_adjacency(text, emitted):
    """Parse '+1 Science per 2 Rainforest; +2 Gold per river; ...' into typed rows; rows about
    things the core does not model (wonders, natural wonders, districts not generated) are dropped."""
    out = []
    for part in [p.strip() for p in text.split(";") if p.strip()]:
        m = re.fullmatch(r"\+(\d+) (\w+) per (2 )?(.+)", part)
        if not m:
            raise ValueError(f"adjacency: {part!r}")
        row = {"yield": YIELD_WORDS[m.group(2)], "amount": int(m.group(1))}
        if m.group(3):
            row["tilesRequired"] = 2
        thing = m.group(4)
        if thing == "Mountain":
            row["kind"] = "MOUNTAIN"
        elif thing == "river":
            row["kind"] = "RIVER"
        elif thing == "district":
            row["kind"] = "ANY_DISTRICT"
        elif thing == "Strategic resource":
            row["kind"] = "STRATEGIC_RESOURCE"
        elif thing == "sea resource":
            row["kind"] = "SEA_RESOURCE"
        elif thing in FEATURE_NAMES:
            row["kind"], row["ref"] = "FEATURE", FEATURE_NAMES[thing]
        elif thing in IMPROVEMENT_NAMES:
            row["kind"], row["ref"] = "IMPROVEMENT", IMPROVEMENT_NAMES[thing]
        elif "DISTRICT_" + snake(thing) in emitted:
            row["kind"], row["ref"] = "DISTRICT", "DISTRICT_" + snake(thing)
        else:
            continue
        out.append(row)
    return out


def gen_districts():
    """City Center (hit points, strike range) and the placeable specialty districts."""
    stats = {row["District"]: row for row in table(SPEC / "districts.md", "District stats") if not row["Unique to"]}
    extra = {row["District"]: row for row in table(SPEC / "districts.md", "District adjacency, placement, trade-route yields and modifiers")}
    names = ["City Center"] + PLACEABLE_DISTRICTS
    emitted = {"DISTRICT_" + snake(n) for n in names}
    out = []
    for name in names:
        row = stats[name]
        d = {"id": "DISTRICT_" + snake(name), "name": name}
        if row["HP"]:
            d["hp"] = num(row["HP"])
        m = re.search(r"attack range (\d+)", row["Placement/flags"])
        if m:
            d["attackRange"] = int(m.group(1))
        if name != "City Center":
            d["unlock"] = unlock_id(row["Unlock"])
            d["cost"] = num(row["Base cost"])
            model, param = row["Cost progression"].split()
            d["costProgression"] = model
            d["costDiscountPercent"] = num(param) if model == "NUM_UNDER_AVG_PLUS_TECH" else 0
            d["needsPopulation"] = row["Needs pop"] == "yes"
            d["maintenance"] = num(row["Maintenance"])
            if "not adjacent to City Center" in row["Placement/flags"]:
                d["notAdjacentToCityCenter"] = True
            if "coast/lake" in row["Placement/flags"]:
                d["water"] = True  # on Coast or Lake next to land
            d["adjacency"] = district_adjacency(extra[name]["Adjacency rules"], emitted)
        out.append(d)
    return {"districts": out}


def gen_happiness():
    out = []
    for row in table(SPEC / "eras-moments-loyalty.md", "Amenities (happiness levels)"):
        h = {"id": "HAPPINESS_" + snake(row["Level"]),
             "growthPercent": int(num(row["Growth %"])), "yieldPercent": int(num(row["Non-food yield %"])),
             "loyaltyPerTurn": int(num(row["Loyalty/turn [R&F]"]))}
        if row["Min amenity balance"]:
            h["minBalance"] = num(row["Min amenity balance"])
        out.append(h)
    return out


def gen_loyalty_levels():
    out = []
    for row in table(SPEC / "eras-moments-loyalty.md", "Loyalty levels [R&F]"):
        low = row["Loyalty range"].split("-")[0]
        out.append({"id": "LOYALTY_" + snake(row["Level"]), "minLoyalty": int(num(low)),
                    "yieldPercent": int(round(num(row["Yield change"]) * 100)),
                    "growthPercent": int(round(num(row["Growth multiplier"]) * 100))})
    return out


def gen_globals():
    values = {}
    for _, header, rows in tables(SPEC / "global-parameters.md"):
        if header[:2] != ["Parameter", "Value"]:
            continue
        for row in rows:
            try:
                values[row["Parameter"]] = num(row["Value"])
            except ValueError:
                pass  # text-valued parameters are not rules numbers
    return {"globals": dict(sorted(values.items())), "happinessLevels": gen_happiness(),
            "loyaltyLevels": gen_loyalty_levels()}


def gen_improvements():
    tnames = terrain_names()
    resources = {}
    for sec in ("Bonus resources", "Luxury resources", "Strategic resources"):
        for r in table(SPEC / "terrain-features-resources.md", sec):
            resources[r["Resource"]] = "RESOURCE_" + snake(r["Resource"])
    rows = [r for r in table(SPEC / "improvements.md", "Improvements")
            if r["Built by"] == "Builder" and not r["Unique to"]]
    ids = {r["Improvement"]: "IMPROVEMENT_" + snake(r["Improvement"]) for r in rows}
    out = []
    for row in rows:
        i = {"id": ids[row["Improvement"]], "name": row["Improvement"], "yields": yields(row["Base yields"])}
        if row["Unlock"]:
            i["unlock"] = unlock_id(row["Unlock"])
        terr, feat = [], []
        for v in (x.strip() for x in row["Valid terrain/feature"].split(",")):
            if not v:
                continue
            if v in tnames:
                terr.append(tnames[v])
            elif v in FEATURE_IDS:
                feat.append(FEATURE_IDS[v])
            elif v == "Mountain":
                terr += [tnames[b] + "_MOUNTAIN" for b in ("Grassland", "Plains", "Desert", "Tundra", "Snow")]
            else:
                raise ValueError(f"improvement {row['Improvement']}: unknown place {v!r}")
        i["validTerrains"], i["validFeatures"] = terr, feat
        i["validResources"] = [resources[x.strip()] for x in row["Valid resources"].split(",") if x.strip()]
        bonus = []
        for part in filter(None, (x.strip() for x in row["Bonus yields"].split(","))):
            m = re.fullmatch(r"\+(\d+) (\w+) With (.+)", part)
            bonus.append({"yield": YIELD_WORDS[m.group(2)], "amount": int(m.group(1)), "unlock": unlock_id(m.group(3))})
        if bonus:
            i["bonusYields"] = bonus
        adjacency = []
        for part in filter(None, (x.strip() for x in row["Adjacency"].split(";"))):
            m = re.fullmatch(r"\+(\d+) (\w+) per (?:(\d+) )?(.+?)(?: \((.+)\))?", part)
            if not m or m.group(4) not in ids:
                continue  # adjacency to districts and unique improvements arrives with them
            a = {"yield": YIELD_WORDS[m.group(2)], "amount": int(m.group(1)), "per": int(m.group(3) or 1),
                 "improvement": ids[m.group(4)]}
            for cond in filter(None, (c.strip() for c in (m.group(5) or "").split(","))):
                c = re.fullmatch(r"(needs|obsolete with) (.+)", cond)
                a["needs" if c.group(1) == "needs" else "obsoleteWith"] = unlock_id(c.group(2))
            adjacency.append(a)
        if adjacency:
            i["adjacency"] = adjacency
        m = re.fullmatch(r"(\d+)(?: \(per (\d+) tiles\))?", row["Housing"])
        if m and int(m.group(1)):
            i["housing"] = int(m.group(1)) / int(m.group(2) or 1)
        out.append(i)
    return {"improvements": out}


# ------------------------------------------------------------ research trees

ERAS = ["Ancient", "Classical", "Medieval", "Renaissance", "Industrial", "Modern", "Atomic",
        "Information", "Future"]


def tree_rows(kind):
    """(era id, row) for every node of the tech ("technologies") or civic ("civics") tree."""
    for section, _, rows in tables(SPEC / f"{kind}.md"):
        m = re.fullmatch(r"(\w+) Era", section or "")
        if m and m.group(1) in ERAS:
            for row in rows:
                yield "ERA_" + m.group(1).upper(), row


def node_names():
    names = {}
    for era, row in tree_rows("technologies"):
        names[row["Technology"]] = "TECH_" + snake(row["Technology"])
    for era, row in tree_rows("civics"):
        names[row["Civic"]] = "CIVIC_" + snake(row["Civic"])
    return names


def unlock_id(name):
    ids = node_names()
    if name not in ids:
        raise ValueError(f"unlock {name!r} is neither a technology nor a civic")
    return ids[name]


def singulars(name):
    yield name
    if name.endswith("ies"):
        yield name[:-3] + "y"
    if name.endswith("s"):
        yield name[:-1]
    if name.endswith("es"):
        yield name[:-2]


def lookup(name, ids):
    for n in singulars(name):
        if n in ids:
            return ids[n]
    return None


def boost_trigger(text):
    """Turn a boost condition into {type, ref, count}. "NONE" means no condition
    can earn it; conditions the rules core cannot read are "UNTRACKED"."""
    units = {r["Unit"]: "UNIT_" + snake(r["Unit"]) for r in table(SPEC / "units.md", "Units") if not r.get("Unique to")}
    buildings = {r["Building"]: "BUILDING_" + snake(r["Building"])
                 for r in table(SPEC / "buildings.md", "Buildings") if not r.get("Unique to")}
    districts = {r["District"]: "DISTRICT_" + snake(r["District"])
                 for r in table(SPEC / "districts.md", "District stats") if not r.get("Unique to")}
    improvements = {r["Improvement"]: "IMPROVEMENT_" + snake(r["Improvement"])
                    for r in table(SPEC / "improvements.md", "Improvements") if not r.get("Unique to")}
    resources = {}
    for sec in ("Bonus resources", "Luxury resources", "Strategic resources"):
        for r in table(SPEC / "terrain-features-resources.md", sec):
            resources[r["Resource"]] = "RESOURCE_" + snake(r["Resource"])
    nodes = node_names()
    t = (text or "").strip()
    count = lambda w: 1 if w in ("a", "an") else int(w)
    m = re.fullmatch(r"build (a|an|\d+) (.+?)( on a resource)?", t)
    if m:
        n, what, on_res = count(m.group(1)), m.group(2), bool(m.group(3))
        if on_res and lookup(what, improvements):
            return {"type": "IMPROVEMENT_ON_RESOURCE", "ref": lookup(what, improvements), "count": n}
        for kind, ids in (("BUILDING", buildings), ("DISTRICT", districts), ("IMPROVEMENT", improvements)):
            ref = lookup(what, ids)
            if ref and not on_res:
                return {"type": kind, "ref": ref, "count": n}
    m = re.fullmatch(r"(?:own|train) (a|an|\d+) (.+)", t)
    if m and lookup(m.group(2), units):
        return {"type": "OWN_UNITS", "ref": lookup(m.group(2), units), "count": count(m.group(1))}
    m = re.fullmatch(r"research (.+)", t)
    if m and m.group(1) in nodes:
        return {"type": "TECH", "ref": nodes[m.group(1)]}
    m = re.fullmatch(r"complete the civic (.+)", t)
    if m and m.group(1) in nodes:
        return {"type": "CIVIC", "ref": nodes[m.group(1)]}
    m = re.fullmatch(r"adopt a Tier(\d) government", t)
    if m:
        return {"type": "GOVERNMENT_TIER", "count": int(m.group(1))}
    m = re.fullmatch(r"reach (\d+) total population", t)
    if m:
        return {"type": "TOTAL_POPULATION", "count": int(m.group(1))}
    m = re.fullmatch(r"grow a city to (\d+) population", t)
    if m:
        return {"type": "CITY_POPULATION", "count": int(m.group(1))}
    m = re.fullmatch(r"have (\d+) land combat units", t)
    if m:
        return {"type": "LAND_COMBAT_UNITS", "count": int(m.group(1))}
    if t == "found a coastal city":
        return {"type": "COASTAL_CITY"}
    m = re.fullmatch(r"improve (.+)", t)
    if m and m.group(1) in resources:
        return {"type": "IMPROVE_RESOURCE", "ref": resources[m.group(1)]}
    m = re.fullmatch(r"improve (\d+) tiles", t)
    if m:
        return {"type": "IMPROVED_TILES", "count": int(m.group(1))}
    m = re.fullmatch(r"have (\d+) different specialty districts", t)
    if m:
        return {"type": "SPECIALTY_DISTRICTS", "count": int(m.group(1))}
    if not t or t.lower().startswith("none"):
        return {"type": "NONE"}
    return {"type": "UNTRACKED"}


def gen_tree(kind, name_col, prefix, key):
    ids = node_names()
    out = []
    for era, row in tree_rows(kind):
        n = {"id": prefix + snake(row[name_col]), "name": row[name_col], "era": era, "cost": num(row["Cost"])}
        prereqs = [ids[x.strip()] for x in row["Prerequisites"].split(",") if x.strip()]
        if prereqs:
            n["prereqs"] = prereqs
        other = row.get("Other effects (envoys, governor titles, slots...)") or row.get("Other effects", "")
        flags = [f for text, f in (("grant combat adjacency", "COMBAT_ADJACENCY"),
                                   ("adjust player enforce borders", "ENFORCE_BORDERS"),
                                   ("can enter Ocean", "OCEAN")) if text in other]
        unlocks = row.get("Unlocks", "")
        if re.search(r"(^|; )embark all\b", unlocks):
            flags.append("EMBARK_ALL")
        if flags:
            n["effects"] = flags
        m = re.search(r"(?:^|; )embark (Builder|Trader)\b", unlocks)
        if m:
            n["embarkUnit"] = "UNIT_" + snake(m.group(1))
        m = re.search(r"\+(\d+) Movement while embarked", other)
        if m:
            n["embarkedMoves"] = int(m.group(1))
        if row["Boost %"]:
            n["boost"] = {"percent": num(row["Boost %"]), "text": row["Boost condition"],
                          **boost_trigger(row["Boost condition"])}
        out.append(n)
    # Future-era nodes get random prerequisites in Civ VI (Tree Randomizer).
    # Sovereign: a Future node without prerequisites needs the whole Information era.
    info = [n["id"] for n in out if n["era"] == "ERA_INFORMATION"]
    for n in out:
        if n["era"] == "ERA_FUTURE" and "prereqs" not in n:
            n["prereqs"] = info
    doc = {key: out}
    if kind == "technologies":
        stats = {r["Era"]: r for r in table(SPEC / "eras-moments-loyalty.md", "Eras")}
        doc["eras"] = [{"id": "ERA_" + e.upper(), "name": e,
                        "embarkedStrength": num(stats[e + " Era"]["Embarked strength"]),
                        "greatPersonBaseCost": num(stats[e + " Era"]["GP base cost"])} for e in ERAS]
    return doc


def gen_governments():
    ids = node_names()
    out = []
    for row in table(SPEC / "governments-policies.md", "Governments"):
        g = {"id": "GOVERNMENT_" + snake(row["Government"]), "name": row["Government"],
             "tier": num(row["Tier"].replace("Tier", "")),
             "slots": {"MILITARY": num(row["Military"]), "ECONOMIC": num(row["Economic"]),
                       "DIPLOMATIC": num(row["Diplomatic"]), "WILDCARD": num(row["Wildcard"])}}
        if row["Unlock"]:
            g["unlock"] = ids[row["Unlock"]]
        out.append(g)
    return {"governments": out}


def gen_policies():
    ids = node_names()
    govs = {r["Government"]: "GOVERNMENT_" + snake(r["Government"])
            for r in table(SPEC / "governments-policies.md", "Governments")}
    policy_ids = {}
    for section in ("Military policies", "Economic policies", "Diplomatic policies", "Wildcard policies",
                    "Great Person policies"):
        for row in table(SPEC / "governments-policies.md", section):
            policy_ids[row["Policy"]] = "POLICY_" + snake(row["Policy"])
    out = []
    for section, slot in (("Military policies", "MILITARY"), ("Economic policies", "ECONOMIC"),
                          ("Diplomatic policies", "DIPLOMATIC"), ("Wildcard policies", "WILDCARD"),
                          ("Great Person policies", "GREAT_PERSON")):
        for row in table(SPEC / "governments-policies.md", section):
            p = {"id": "POLICY_" + snake(row["Policy"]), "name": row["Policy"], "slot": slot}
            if row["Unlock"] in ids:
                p["unlock"] = ids[row["Unlock"]]
            elif row["Unlock"] == "government":
                p["legacy"] = True  # legacy cards arrive with eras and legacy rules
            # A card goes obsolete once any of its replacement cards is unlocked.
            obsolete = [policy_ids[x.strip()] for x in row["Obsoleted by"].split(",") if x.strip()]
            if obsolete:
                p["obsoletedBy"] = obsolete
            if row["Age requirement [R&F]"]:
                p["ageRequirement"] = row["Age requirement [R&F]"]
            if row["Government-exclusive [GS]"]:
                p["government"] = govs[row["Government-exclusive [GS]"]]
            out.append(p)
    return {"policies": out}


HEADER = {"_generated": "by tools/rules_gen/gen_rules.py from specs/civ6/data; do not edit by hand"}


def render(doc):
    return json.dumps({**HEADER, **doc}, indent=1, ensure_ascii=False) + "\n"


def main():
    check = "--check" in sys.argv
    outputs = {
        "globals.json": gen_globals(),
        "terrain.json": gen_terrain(),
        "resources.json": gen_resources(),
        "promotions.json": gen_promotions(),
        "units.json": gen_units(),
        "buildings.json": gen_buildings(),
        "districts.json": gen_districts(),
        "barbarians.json": gen_barbarians(),
        "techs.json": gen_tree("technologies", "Technology", "TECH_", "techs"),
        "civics.json": gen_tree("civics", "Civic", "CIVIC_", "civics"),
        "governments.json": gen_governments(),
        "policies.json": gen_policies(),
        "improvements.json": gen_improvements(),
    }
    stale = []
    for name, doc in outputs.items():
        path = OUT / name
        text = render(doc)
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    if stale:
        print("stale generated rules:", ", ".join(stale), "- rerun tools/rules_gen/gen_rules.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
